/*
 * Copyright (c) 2004-2026 The mzmine Development Team
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

// Generated by jextract

package io.github.mzmine.modules.io.import_rawdata_wiff2;

import io.github.mzmine.util.files.FileAndPathUtil;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SymbolLookup;
import java.lang.invoke.MethodHandle;

/**
 * static final SymbolLookup SYMBOL_LOOKUP = getSymbolLookup();
 * <pre>
 * {@code
 *   static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.libraryLookup(
 *       FileAndPathUtil.resolveInExternalToolsDir(
 *           "sciex_wiff2/%s".formatted(System.mapLibraryName("Wiff2Launcher"))).toPath(),
 *       LIBRARY_ARENA).or(SymbolLookup.loaderLookup()).or(Linker.nativeLinker().defaultLookup());
 *   }
 *   </pre>
 */

public class Wiff2LauncherLib_h extends Wiff2LauncherLib_h$shared {

  Wiff2LauncherLib_h() {
    // Should not be called directly
  }

  static final Arena LIBRARY_ARENA = Arena.ofAuto();

  static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.libraryLookup(
      FileAndPathUtil.resolveInExternalToolsDir(
          "sciex_wiff2/%s".formatted(System.mapLibraryName("Wiff2Launcher"))).toPath(),
      LIBRARY_ARENA).or(SymbolLookup.loaderLookup()).or(Linker.nativeLinker().defaultLookup());

  private static class wiff2_launch_server {

    public static final FunctionDescriptor DESC = FunctionDescriptor.of(
        Wiff2LauncherLib_h.C_LONG_LONG, Wiff2LauncherLib_h.C_POINTER);

    public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("wiff2_launch_server");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang = c:
   * long long wiff2_launch_server(const char *server_path)
   *}
   */
  public static FunctionDescriptor wiff2_launch_server$descriptor() {
    return wiff2_launch_server.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang = c:
   * long long wiff2_launch_server(const char *server_path)
   *}
   */
  public static MethodHandle wiff2_launch_server$handle() {
    return wiff2_launch_server.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang = c:
   * long long wiff2_launch_server(const char *server_path)
   *}
   */
  public static MemorySegment wiff2_launch_server$address() {
    return wiff2_launch_server.ADDR;
  }

  /**
   * {@snippet lang = c:
   * long long wiff2_launch_server(const char *server_path)
   *}
   */
  public static long wiff2_launch_server(MemorySegment server_path) {
    var mh$ = wiff2_launch_server.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("wiff2_launch_server", server_path);
      }
      return (long) mh$.invokeExact(server_path);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }
}

