// Generated by jextract

package io.github.mzmine.modules.io.import_rawdata_bruker_tsf.datamodel;

import java.lang.invoke.*;
import java.lang.foreign.*;

/**
 * {@snippet lang=c :
 * typedef uint32_t (BdalTimsConversionFunction)(uint64_t, int64_t, const double *, double *, uint32_t)
 * }
 */
public final class BdalTimsConversionFunction {

    private BdalTimsConversionFunction() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(long handle, long frame_id, MemorySegment in, MemorySegment out, int cnt);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        TSFLib.C_INT,
        TSFLib.C_LONG_LONG,
        TSFLib.C_LONG_LONG,
        TSFLib.C_POINTER,
        TSFLib.C_POINTER,
        TSFLib.C_INT
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = TSFLib.upcallHandle(BdalTimsConversionFunction.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(BdalTimsConversionFunction.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr, long handle, long frame_id, MemorySegment in, MemorySegment out, int cnt) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, handle, frame_id, in, out, cnt);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

