// Generated by jextract

package io.github.mzmine.modules.io.import_rawdata_bruker_tsf.datamodel;

import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     uint32_t *optional_sweep_id;
 *     uint32_t *optional_mrms_scan_nr;
 *     uint64_t tims_gates_len;
 *     gated_tims_gate *tims_gates;
 * }
 * }
 */
public class gated_tims_info_type {

    gated_tims_info_type() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TSFLib.C_POINTER.withName("optional_sweep_id"),
        TSFLib.C_POINTER.withName("optional_mrms_scan_nr"),
        TSFLib.C_LONG_LONG.withName("tims_gates_len"),
        TSFLib.C_POINTER.withName("tims_gates")
    ).withName("$anon$66:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout optional_sweep_id$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("optional_sweep_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t *optional_sweep_id
     * }
     */
    public static final AddressLayout optional_sweep_id$layout() {
        return optional_sweep_id$LAYOUT;
    }

    private static final long optional_sweep_id$OFFSET = $LAYOUT.byteOffset(groupElement("optional_sweep_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t *optional_sweep_id
     * }
     */
    public static final long optional_sweep_id$offset() {
        return optional_sweep_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t *optional_sweep_id
     * }
     */
    public static MemorySegment optional_sweep_id(MemorySegment struct) {
        return struct.get(optional_sweep_id$LAYOUT, optional_sweep_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t *optional_sweep_id
     * }
     */
    public static void optional_sweep_id(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(optional_sweep_id$LAYOUT, optional_sweep_id$OFFSET, fieldValue);
    }

    private static final AddressLayout optional_mrms_scan_nr$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("optional_mrms_scan_nr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t *optional_mrms_scan_nr
     * }
     */
    public static final AddressLayout optional_mrms_scan_nr$layout() {
        return optional_mrms_scan_nr$LAYOUT;
    }

    private static final long optional_mrms_scan_nr$OFFSET = $LAYOUT.byteOffset(groupElement("optional_mrms_scan_nr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t *optional_mrms_scan_nr
     * }
     */
    public static final long optional_mrms_scan_nr$offset() {
        return optional_mrms_scan_nr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t *optional_mrms_scan_nr
     * }
     */
    public static MemorySegment optional_mrms_scan_nr(MemorySegment struct) {
        return struct.get(optional_mrms_scan_nr$LAYOUT, optional_mrms_scan_nr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t *optional_mrms_scan_nr
     * }
     */
    public static void optional_mrms_scan_nr(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(optional_mrms_scan_nr$LAYOUT, optional_mrms_scan_nr$OFFSET, fieldValue);
    }

    private static final OfLong tims_gates_len$LAYOUT = (OfLong)$LAYOUT.select(groupElement("tims_gates_len"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t tims_gates_len
     * }
     */
    public static final OfLong tims_gates_len$layout() {
        return tims_gates_len$LAYOUT;
    }

    private static final long tims_gates_len$OFFSET = $LAYOUT.byteOffset(groupElement("tims_gates_len"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t tims_gates_len
     * }
     */
    public static final long tims_gates_len$offset() {
        return tims_gates_len$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t tims_gates_len
     * }
     */
    public static long tims_gates_len(MemorySegment struct) {
        return struct.get(tims_gates_len$LAYOUT, tims_gates_len$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t tims_gates_len
     * }
     */
    public static void tims_gates_len(MemorySegment struct, long fieldValue) {
        struct.set(tims_gates_len$LAYOUT, tims_gates_len$OFFSET, fieldValue);
    }

    private static final AddressLayout tims_gates$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("tims_gates"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * gated_tims_gate *tims_gates
     * }
     */
    public static final AddressLayout tims_gates$layout() {
        return tims_gates$LAYOUT;
    }

    private static final long tims_gates$OFFSET = $LAYOUT.byteOffset(groupElement("tims_gates"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * gated_tims_gate *tims_gates
     * }
     */
    public static final long tims_gates$offset() {
        return tims_gates$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * gated_tims_gate *tims_gates
     * }
     */
    public static MemorySegment tims_gates(MemorySegment struct) {
        return struct.get(tims_gates$LAYOUT, tims_gates$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * gated_tims_gate *tims_gates
     * }
     */
    public static void tims_gates(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(tims_gates$LAYOUT, tims_gates$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

