// Generated by jextract

package io.github.mzmine.modules.io.import_rawdata_bruker_tsf.datamodel;

import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int ndelay;
 *     int ncycles;
 *     double dv_start;
 *     double dv_end;
 * }
 * }
 */
public class linear_voltage_ramp {

    linear_voltage_ramp() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TSFLib.C_INT.withName("ndelay"),
        TSFLib.C_INT.withName("ncycles"),
        TSFLib.C_DOUBLE.withName("dv_start"),
        TSFLib.C_DOUBLE.withName("dv_end")
    ).withName("$anon$40:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt ndelay$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ndelay"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int ndelay
     * }
     */
    public static final OfInt ndelay$layout() {
        return ndelay$LAYOUT;
    }

    private static final long ndelay$OFFSET = $LAYOUT.byteOffset(groupElement("ndelay"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int ndelay
     * }
     */
    public static final long ndelay$offset() {
        return ndelay$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int ndelay
     * }
     */
    public static int ndelay(MemorySegment struct) {
        return struct.get(ndelay$LAYOUT, ndelay$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int ndelay
     * }
     */
    public static void ndelay(MemorySegment struct, int fieldValue) {
        struct.set(ndelay$LAYOUT, ndelay$OFFSET, fieldValue);
    }

    private static final OfInt ncycles$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ncycles"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int ncycles
     * }
     */
    public static final OfInt ncycles$layout() {
        return ncycles$LAYOUT;
    }

    private static final long ncycles$OFFSET = $LAYOUT.byteOffset(groupElement("ncycles"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int ncycles
     * }
     */
    public static final long ncycles$offset() {
        return ncycles$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int ncycles
     * }
     */
    public static int ncycles(MemorySegment struct) {
        return struct.get(ncycles$LAYOUT, ncycles$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int ncycles
     * }
     */
    public static void ncycles(MemorySegment struct, int fieldValue) {
        struct.set(ncycles$LAYOUT, ncycles$OFFSET, fieldValue);
    }

    private static final OfDouble dv_start$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("dv_start"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double dv_start
     * }
     */
    public static final OfDouble dv_start$layout() {
        return dv_start$LAYOUT;
    }

    private static final long dv_start$OFFSET = $LAYOUT.byteOffset(groupElement("dv_start"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double dv_start
     * }
     */
    public static final long dv_start$offset() {
        return dv_start$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double dv_start
     * }
     */
    public static double dv_start(MemorySegment struct) {
        return struct.get(dv_start$LAYOUT, dv_start$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double dv_start
     * }
     */
    public static void dv_start(MemorySegment struct, double fieldValue) {
        struct.set(dv_start$LAYOUT, dv_start$OFFSET, fieldValue);
    }

    private static final OfDouble dv_end$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("dv_end"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double dv_end
     * }
     */
    public static final OfDouble dv_end$layout() {
        return dv_end$LAYOUT;
    }

    private static final long dv_end$OFFSET = $LAYOUT.byteOffset(groupElement("dv_end"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double dv_end
     * }
     */
    public static final long dv_end$offset() {
        return dv_end$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double dv_end
     * }
     */
    public static double dv_end(MemorySegment struct) {
        return struct.get(dv_end$LAYOUT, dv_end$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double dv_end
     * }
     */
    public static void dv_end(MemorySegment struct, double fieldValue) {
        struct.set(dv_end$LAYOUT, dv_end$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

