// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

@com.google.protobuf.Generated
public interface BinaryDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Clearcore2.SampleData.DataAccessApi.V002.BinaryData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * attributes describing the values
   * for example: the following will be provided
   * MS:1000523 64-bit float
   * MS:1000514 m/z array OR MS:1000515 intensity array
   * optional MS:1000574 zlib compression
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
   */
  java.util.List<ControlledVocabularyParameter>
      getAttributesList();
  /**
   * <pre>
   * attributes describing the values
   * for example: the following will be provided
   * MS:1000523 64-bit float
   * MS:1000514 m/z array OR MS:1000515 intensity array
   * optional MS:1000574 zlib compression
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
   */
  ControlledVocabularyParameter getAttributes(int index);
  /**
   * <pre>
   * attributes describing the values
   * for example: the following will be provided
   * MS:1000523 64-bit float
   * MS:1000514 m/z array OR MS:1000515 intensity array
   * optional MS:1000574 zlib compression
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
   */
  int getAttributesCount();
  /**
   * <pre>
   * attributes describing the values
   * for example: the following will be provided
   * MS:1000523 64-bit float
   * MS:1000514 m/z array OR MS:1000515 intensity array
   * optional MS:1000574 zlib compression
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
   */
  java.util.List<? extends ControlledVocabularyParameterOrBuilder>
      getAttributesOrBuilderList();
  /**
   * <pre>
   * attributes describing the values
   * for example: the following will be provided
   * MS:1000523 64-bit float
   * MS:1000514 m/z array OR MS:1000515 intensity array
   * optional MS:1000574 zlib compression
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
   */
  ControlledVocabularyParameterOrBuilder getAttributesOrBuilder(
      int index);

  /**
   * <pre>
   * the values in a binary format 
   * </pre>
   *
   * <code>bytes Values = 2;</code>
   * @return The values.
   */
  com.google.protobuf.ByteString getValues();
}
