// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

@com.google.protobuf.Generated
public interface CollisionEnergyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Clearcore2.SampleData.DataAccessApi.V002.CollisionEnergy)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Collision energy at the start of the collision energy ramp. see MS_1002013
   * </pre>
   *
   * <code>double CollisionEnergyRampStart = 1;</code>
   * @return The collisionEnergyRampStart.
   */
  double getCollisionEnergyRampStart();

  /**
   * <pre>
   * Collision energy at the end of the collision energy ramp. see MS_1002014
   * </pre>
   *
   * <code>double CollisionEnergyRampEnd = 2;</code>
   * @return The collisionEnergyRampEnd.
   */
  double getCollisionEnergyRampEnd();
}
