// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

@com.google.protobuf.Generated
public interface CycleRangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Clearcore2.SampleData.DataAccessApi.V002.CycleRange)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * represent retention time relative to the start of the sample. 
   * </pre>
   *
   * <code>int32 Start = 1;</code>
   * @return The start.
   */
  int getStart();

  /**
   * <pre>
   * represent retention time relative to the start of the sample. 
   * </pre>
   *
   * <code>int32 End = 2;</code>
   * @return The end.
   */
  int getEnd();
}
