// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

/**
 * <pre>
 * MS:1000235 Total ion chromatogram
 * </pre>
 *
 * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.ExperimentTic}
 */
@com.google.protobuf.Generated
public final class ExperimentTic extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Clearcore2.SampleData.DataAccessApi.V002.ExperimentTic)
    ExperimentTicOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "ExperimentTic");
  }
  // Use ExperimentTic.newBuilder() to construct.
  private ExperimentTic(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ExperimentTic() {
    experimentId_ = "";
    sampleId_ = "";
    data_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_ExperimentTic_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_ExperimentTic_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic.class, io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic.Builder.class);
  }

  public static final int EXPERIMENTID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object experimentId_ = "";
  /**
   * <pre>
   * The id of the experiment used to acquire this Tic
   * </pre>
   *
   * <code>string ExperimentId = 1;</code>
   * @return The experimentId.
   */
  @java.lang.Override
  public java.lang.String getExperimentId() {
    java.lang.Object ref = experimentId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      experimentId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The id of the experiment used to acquire this Tic
   * </pre>
   *
   * <code>string ExperimentId = 1;</code>
   * @return The bytes for experimentId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExperimentIdBytes() {
    java.lang.Object ref = experimentId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      experimentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SAMPLEID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sampleId_ = "";
  /**
   * <pre>
   * The sample identifier 
   * </pre>
   *
   * <code>string SampleId = 2;</code>
   * @return The sampleId.
   */
  @java.lang.Override
  public java.lang.String getSampleId() {
    java.lang.Object ref = sampleId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sampleId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The sample identifier 
   * </pre>
   *
   * <code>string SampleId = 2;</code>
   * @return The bytes for sampleId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSampleIdBytes() {
    java.lang.Object ref = sampleId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sampleId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData> data_;
  /**
   * <pre>
   * the actual binary data. 
   * Usually, there will be at least 2 collections ( Xs and Ys ) 
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
   */
  @java.lang.Override
  public java.util.List<io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData> getDataList() {
    return data_;
  }
  /**
   * <pre>
   * the actual binary data. 
   * Usually, there will be at least 2 collections ( Xs and Ys ) 
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryDataOrBuilder> 
      getDataOrBuilderList() {
    return data_;
  }
  /**
   * <pre>
   * the actual binary data. 
   * Usually, there will be at least 2 collections ( Xs and Ys ) 
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
   */
  @java.lang.Override
  public int getDataCount() {
    return data_.size();
  }
  /**
   * <pre>
   * the actual binary data. 
   * Usually, there will be at least 2 collections ( Xs and Ys ) 
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
   */
  @java.lang.Override
  public io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData getData(int index) {
    return data_.get(index);
  }
  /**
   * <pre>
   * the actual binary data. 
   * Usually, there will be at least 2 collections ( Xs and Ys ) 
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
   */
  @java.lang.Override
  public io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryDataOrBuilder getDataOrBuilder(
      int index) {
    return data_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(experimentId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, experimentId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sampleId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, sampleId_);
    }
    for (int i = 0; i < data_.size(); i++) {
      output.writeMessage(3, data_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(experimentId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, experimentId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sampleId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, sampleId_);
    }
    for (int i = 0; i < data_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, data_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic)) {
      return super.equals(obj);
    }
    io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic other = (io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic) obj;

    if (!getExperimentId()
        .equals(other.getExperimentId())) return false;
    if (!getSampleId()
        .equals(other.getSampleId())) return false;
    if (!getDataList()
        .equals(other.getDataList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EXPERIMENTID_FIELD_NUMBER;
    hash = (53 * hash) + getExperimentId().hashCode();
    hash = (37 * hash) + SAMPLEID_FIELD_NUMBER;
    hash = (53 * hash) + getSampleId().hashCode();
    if (getDataCount() > 0) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getDataList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * MS:1000235 Total ion chromatogram
   * </pre>
   *
   * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.ExperimentTic}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Clearcore2.SampleData.DataAccessApi.V002.ExperimentTic)
      io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTicOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_ExperimentTic_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_ExperimentTic_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic.class, io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic.Builder.class);
    }

    // Construct using io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      experimentId_ = "";
      sampleId_ = "";
      if (dataBuilder_ == null) {
        data_ = java.util.Collections.emptyList();
      } else {
        data_ = null;
        dataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_ExperimentTic_descriptor;
    }

    @java.lang.Override
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic getDefaultInstanceForType() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic build() {
      io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic buildPartial() {
      io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic result = new io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic result) {
      if (dataBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
    }

    private void buildPartial0(io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.experimentId_ = experimentId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sampleId_ = sampleId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic) {
        return mergeFrom((io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic other) {
      if (other == io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic.getDefaultInstance()) return this;
      if (!other.getExperimentId().isEmpty()) {
        experimentId_ = other.experimentId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getSampleId().isEmpty()) {
        sampleId_ = other.sampleId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (dataBuilder_ == null) {
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
      } else {
        if (!other.data_.isEmpty()) {
          if (dataBuilder_.isEmpty()) {
            dataBuilder_.dispose();
            dataBuilder_ = null;
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000004);
            dataBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetDataFieldBuilder() : null;
          } else {
            dataBuilder_.addAllMessages(other.data_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              experimentId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              sampleId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData m =
                  input.readMessage(
                      io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.parser(),
                      extensionRegistry);
              if (dataBuilder_ == null) {
                ensureDataIsMutable();
                data_.add(m);
              } else {
                dataBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object experimentId_ = "";
    /**
     * <pre>
     * The id of the experiment used to acquire this Tic
     * </pre>
     *
     * <code>string ExperimentId = 1;</code>
     * @return The experimentId.
     */
    public java.lang.String getExperimentId() {
      java.lang.Object ref = experimentId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        experimentId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The id of the experiment used to acquire this Tic
     * </pre>
     *
     * <code>string ExperimentId = 1;</code>
     * @return The bytes for experimentId.
     */
    public com.google.protobuf.ByteString
        getExperimentIdBytes() {
      java.lang.Object ref = experimentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        experimentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The id of the experiment used to acquire this Tic
     * </pre>
     *
     * <code>string ExperimentId = 1;</code>
     * @param value The experimentId to set.
     * @return This builder for chaining.
     */
    public Builder setExperimentId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      experimentId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The id of the experiment used to acquire this Tic
     * </pre>
     *
     * <code>string ExperimentId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearExperimentId() {
      experimentId_ = getDefaultInstance().getExperimentId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The id of the experiment used to acquire this Tic
     * </pre>
     *
     * <code>string ExperimentId = 1;</code>
     * @param value The bytes for experimentId to set.
     * @return This builder for chaining.
     */
    public Builder setExperimentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      experimentId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object sampleId_ = "";
    /**
     * <pre>
     * The sample identifier 
     * </pre>
     *
     * <code>string SampleId = 2;</code>
     * @return The sampleId.
     */
    public java.lang.String getSampleId() {
      java.lang.Object ref = sampleId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sampleId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The sample identifier 
     * </pre>
     *
     * <code>string SampleId = 2;</code>
     * @return The bytes for sampleId.
     */
    public com.google.protobuf.ByteString
        getSampleIdBytes() {
      java.lang.Object ref = sampleId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sampleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The sample identifier 
     * </pre>
     *
     * <code>string SampleId = 2;</code>
     * @param value The sampleId to set.
     * @return This builder for chaining.
     */
    public Builder setSampleId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sampleId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The sample identifier 
     * </pre>
     *
     * <code>string SampleId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSampleId() {
      sampleId_ = getDefaultInstance().getSampleId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The sample identifier 
     * </pre>
     *
     * <code>string SampleId = 2;</code>
     * @param value The bytes for sampleId to set.
     * @return This builder for chaining.
     */
    public Builder setSampleIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sampleId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData> data_ =
      java.util.Collections.emptyList();
    private void ensureDataIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        data_ = new java.util.ArrayList<io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData>(data_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData, io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.Builder, io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryDataOrBuilder> dataBuilder_;

    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
     */
    public java.util.List<io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData> getDataList() {
      if (dataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(data_);
      } else {
        return dataBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
     */
    public int getDataCount() {
      if (dataBuilder_ == null) {
        return data_.size();
      } else {
        return dataBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData getData(int index) {
      if (dataBuilder_ == null) {
        return data_.get(index);
      } else {
        return dataBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
     */
    public Builder setData(
        int index, io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
      } else {
        dataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
     */
    public Builder setData(
        int index, io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.set(index, builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
     */
    public Builder addData(io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
      } else {
        dataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
     */
    public Builder addData(
        int index, io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.add(index, value);
        onChanged();
      } else {
        dataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
     */
    public Builder addData(
        io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.add(builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
     */
    public Builder addData(
        int index, io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.add(index, builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
     */
    public Builder addAllData(
        java.lang.Iterable<? extends io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData> values) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
      } else {
        dataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        dataBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
     */
    public Builder removeData(int index) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.remove(index);
        onChanged();
      } else {
        dataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.Builder getDataBuilder(
        int index) {
      return internalGetDataFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryDataOrBuilder getDataOrBuilder(
        int index) {
      if (dataBuilder_ == null) {
        return data_.get(index);  } else {
        return dataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
     */
    public java.util.List<? extends io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryDataOrBuilder> 
         getDataOrBuilderList() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(data_);
      }
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.Builder addDataBuilder() {
      return internalGetDataFieldBuilder().addBuilder(
          io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.getDefaultInstance());
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.Builder addDataBuilder(
        int index) {
      return internalGetDataFieldBuilder().addBuilder(
          index, io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.getDefaultInstance());
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 3;</code>
     */
    public java.util.List<io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.Builder> 
         getDataBuilderList() {
      return internalGetDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData, io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.Builder, io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryDataOrBuilder> 
        internalGetDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData, io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.Builder, io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryDataOrBuilder>(
                data_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:Clearcore2.SampleData.DataAccessApi.V002.ExperimentTic)
  }

  // @@protoc_insertion_point(class_scope:Clearcore2.SampleData.DataAccessApi.V002.ExperimentTic)
  private static final io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic();
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExperimentTic>
      PARSER = new com.google.protobuf.AbstractParser<ExperimentTic>() {
    @java.lang.Override
    public ExperimentTic parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExperimentTic> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExperimentTic> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.mzmine.modules.io.import_rawdata_wiff2.api.ExperimentTic getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

