// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

@com.google.protobuf.Generated
public interface ExperimentScanRecordsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Clearcore2.SampleData.DataAccessApi.V002.ExperimentScanRecordsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the target sample id
   * </pre>
   *
   * <code>string SampleId = 1;</code>
   * @return The sampleId.
   */
  java.lang.String getSampleId();
  /**
   * <pre>
   * the target sample id
   * </pre>
   *
   * <code>string SampleId = 1;</code>
   * @return The bytes for sampleId.
   */
  com.google.protobuf.ByteString
      getSampleIdBytes();

  /**
   * <pre>
   * the id of the experiment 
   * </pre>
   *
   * <code>string ExperimentId = 2;</code>
   * @return The experimentId.
   */
  java.lang.String getExperimentId();
  /**
   * <pre>
   * the id of the experiment 
   * </pre>
   *
   * <code>string ExperimentId = 2;</code>
   * @return The bytes for experimentId.
   */
  com.google.protobuf.ByteString
      getExperimentIdBytes();

  /**
   * <pre>
   * will be NULL for Non-Tof DataFormat, must be present for Tof Data 
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TofInstrumentParameters TofInstrumentParameters = 3;</code>
   * @return Whether the tofInstrumentParameters field is set.
   */
  boolean hasTofInstrumentParameters();
  /**
   * <pre>
   * will be NULL for Non-Tof DataFormat, must be present for Tof Data 
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TofInstrumentParameters TofInstrumentParameters = 3;</code>
   * @return The tofInstrumentParameters.
   */
  io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters getTofInstrumentParameters();
  /**
   * <pre>
   * will be NULL for Non-Tof DataFormat, must be present for Tof Data 
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TofInstrumentParameters TofInstrumentParameters = 3;</code>
   */
  io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParametersOrBuilder getTofInstrumentParametersOrBuilder();

  /**
   * <pre>
   * scan records
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ScanRecordInfo Scans = 4;</code>
   */
  java.util.List<io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanRecordInfo> 
      getScansList();
  /**
   * <pre>
   * scan records
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ScanRecordInfo Scans = 4;</code>
   */
  io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanRecordInfo getScans(int index);
  /**
   * <pre>
   * scan records
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ScanRecordInfo Scans = 4;</code>
   */
  int getScansCount();
  /**
   * <pre>
   * scan records
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ScanRecordInfo Scans = 4;</code>
   */
  java.util.List<? extends io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanRecordInfoOrBuilder> 
      getScansOrBuilderList();
  /**
   * <pre>
   * scan records
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ScanRecordInfo Scans = 4;</code>
   */
  io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanRecordInfoOrBuilder getScansOrBuilder(
      int index);
}
