// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

@com.google.protobuf.Generated
public interface GetExperimentCyclesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Clearcore2.SampleData.DataAccessApi.V002.GetExperimentCyclesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The id of the experiment for which to retrieve the list of cycles
   * </pre>
   *
   * <code>string ExperimentId = 1;</code>
   * @return The experimentId.
   */
  java.lang.String getExperimentId();
  /**
   * <pre>
   * The id of the experiment for which to retrieve the list of cycles
   * </pre>
   *
   * <code>string ExperimentId = 1;</code>
   * @return The bytes for experimentId.
   */
  com.google.protobuf.ByteString
      getExperimentIdBytes();

  /**
   * <pre>
   * The sample identifier 
   * </pre>
   *
   * <code>string SampleId = 2;</code>
   * @return The sampleId.
   */
  java.lang.String getSampleId();
  /**
   * <pre>
   * The sample identifier 
   * </pre>
   *
   * <code>string SampleId = 2;</code>
   * @return The bytes for sampleId.
   */
  com.google.protobuf.ByteString
      getSampleIdBytes();
}
