// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

@com.google.protobuf.Generated
public interface GetExperimentTicRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Clearcore2.SampleData.DataAccessApi.V002.GetExperimentTicRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the id of the sample
   * </pre>
   *
   * <code>string SampleId = 1;</code>
   * @return The sampleId.
   */
  String getSampleId();
  /**
   * <pre>
   * the id of the sample
   * </pre>
   *
   * <code>string SampleId = 1;</code>
   * @return The bytes for sampleId.
   */
  com.google.protobuf.ByteString
      getSampleIdBytes();

  /**
   * <pre>
   * the id of the experiment
   * </pre>
   *
   * <code>string ExperimentId = 2;</code>
   * @return The experimentId.
   */
  String getExperimentId();
  /**
   * <pre>
   * the id of the experiment
   * </pre>
   *
   * <code>string ExperimentId = 2;</code>
   * @return The bytes for experimentId.
   */
  com.google.protobuf.ByteString
      getExperimentIdBytes();
}
