// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

@com.google.protobuf.Generated
public interface GetMrmXicRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Clearcore2.SampleData.DataAccessApi.V002.GetMrmXicRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the id of the sample 
   * </pre>
   *
   * <code>string SampleId = 1;</code>
   * @return The sampleId.
   */
  java.lang.String getSampleId();
  /**
   * <pre>
   * the id of the sample 
   * </pre>
   *
   * <code>string SampleId = 1;</code>
   * @return The bytes for sampleId.
   */
  com.google.protobuf.ByteString
      getSampleIdBytes();

  /**
   * <pre>
   * &#47; the id of the experiment
   * </pre>
   *
   * <code>string ExperimentId = 2;</code>
   * @return The experimentId.
   */
  java.lang.String getExperimentId();
  /**
   * <pre>
   * &#47; the id of the experiment
   * </pre>
   *
   * <code>string ExperimentId = 2;</code>
   * @return The bytes for experimentId.
   */
  com.google.protobuf.ByteString
      getExperimentIdBytes();

  /**
   * <pre>
   * &#47; the list of mass indices
   * </pre>
   *
   * <code>repeated int32 MassIndexes = 3;</code>
   * @return A list containing the massIndexes.
   */
  java.util.List<java.lang.Integer> getMassIndexesList();
  /**
   * <pre>
   * &#47; the list of mass indices
   * </pre>
   *
   * <code>repeated int32 MassIndexes = 3;</code>
   * @return The count of massIndexes.
   */
  int getMassIndexesCount();
  /**
   * <pre>
   * &#47; the list of mass indices
   * </pre>
   *
   * <code>repeated int32 MassIndexes = 3;</code>
   * @param index The index of the element to return.
   * @return The massIndexes at the given index.
   */
  int getMassIndexes(int index);

  /**
   * <pre>
   * &#47; the range of cycles
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.CycleRange CycleRange = 4;</code>
   * @return Whether the cycleRange field is set.
   */
  boolean hasCycleRange();
  /**
   * <pre>
   * &#47; the range of cycles
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.CycleRange CycleRange = 4;</code>
   * @return The cycleRange.
   */
  io.github.mzmine.modules.io.import_rawdata_wiff2.api.CycleRange getCycleRange();
  /**
   * <pre>
   * &#47; the range of cycles
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.CycleRange CycleRange = 4;</code>
   */
  io.github.mzmine.modules.io.import_rawdata_wiff2.api.CycleRangeOrBuilder getCycleRangeOrBuilder();

  /**
   * <pre>
   * &#47; the range of the time
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange TimeRange = 5;</code>
   * @return Whether the timeRange field is set.
   */
  boolean hasTimeRange();
  /**
   * <pre>
   * &#47; the range of the time
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange TimeRange = 5;</code>
   * @return The timeRange.
   */
  io.github.mzmine.modules.io.import_rawdata_wiff2.api.TimeRange getTimeRange();
  /**
   * <pre>
   * &#47; the range of the time
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange TimeRange = 5;</code>
   */
  io.github.mzmine.modules.io.import_rawdata_wiff2.api.TimeRangeOrBuilder getTimeRangeOrBuilder();
}
