// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

@com.google.protobuf.Generated
public interface GetWavelengthSpectraRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Clearcore2.SampleData.DataAccessApi.V002.GetWavelengthSpectraRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The window of time used for signal acquisition. If not present, then the open window is assumed
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange Range = 1;</code>
   * @return Whether the range field is set.
   */
  boolean hasRange();
  /**
   * <pre>
   * The window of time used for signal acquisition. If not present, then the open window is assumed
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange Range = 1;</code>
   * @return The range.
   */
  io.github.mzmine.modules.io.import_rawdata_wiff2.api.TimeRange getRange();
  /**
   * <pre>
   * The window of time used for signal acquisition. If not present, then the open window is assumed
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange Range = 1;</code>
   */
  io.github.mzmine.modules.io.import_rawdata_wiff2.api.TimeRangeOrBuilder getRangeOrBuilder();

  /**
   * <pre>
   * the target sample id
   * </pre>
   *
   * <code>string SampleId = 2;</code>
   * @return The sampleId.
   */
  java.lang.String getSampleId();
  /**
   * <pre>
   * the target sample id
   * </pre>
   *
   * <code>string SampleId = 2;</code>
   * @return The bytes for sampleId.
   */
  com.google.protobuf.ByteString
      getSampleIdBytes();

  /**
   * <pre>
   * is requesting channel mode data
   * </pre>
   *
   * <code>bool IsRequestingChannelModeData = 3;</code>
   * @return The isRequestingChannelModeData.
   */
  boolean getIsRequestingChannelModeData();

  /**
   * <pre>
   * the id of the experiment
   * </pre>
   *
   * <code>int32 ExperimentId = 4;</code>
   * @return The experimentId.
   */
  int getExperimentId();
}
