// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

/**
 * <pre>
 * Isolation window parameter.
 * </pre>
 *
 * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.IsolationWindow}
 */
@com.google.protobuf.Generated
public final class IsolationWindow extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Clearcore2.SampleData.DataAccessApi.V002.IsolationWindow)
    IsolationWindowOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "IsolationWindow");
  }
  // Use IsolationWindow.newBuilder() to construct.
  private IsolationWindow(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private IsolationWindow() {
    unitAccession_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_IsolationWindow_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_IsolationWindow_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow.class, io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow.Builder.class);
  }

  public static final int LOWEROFFSET_FIELD_NUMBER = 1;
  private double lowerOffset_ = 0D;
  /**
   * <pre>
   * The extent of the isolation window in m/z below the 
   * isolation window target m/z. The lower and upper 
   * offsets may be asymmetric about the target m/z.
   * see MS:1000828 
   * </pre>
   *
   * <code>double LowerOffset = 1;</code>
   * @return The lowerOffset.
   */
  @java.lang.Override
  public double getLowerOffset() {
    return lowerOffset_;
  }

  public static final int UPPEROFFSET_FIELD_NUMBER = 2;
  private double upperOffset_ = 0D;
  /**
   * <pre>
   * The extent of the isolation window in m/z above the isolation 
   * window target m/z. The lower and upper offsets may be 
   * asymmetric about the target m/z.
   * see MS:1000829
   * </pre>
   *
   * <code>double UpperOffset = 2;</code>
   * @return The upperOffset.
   */
  @java.lang.Override
  public double getUpperOffset() {
    return upperOffset_;
  }

  public static final int ISOLATIONWINDOWTARGET_FIELD_NUMBER = 3;
  private double isolationWindowTarget_ = 0D;
  /**
   * <pre>
   * The primary or reference m/z about which the isolation 
   * window is defined. 
   * see  MS:1000827
   * </pre>
   *
   * <code>double IsolationWindowTarget = 3;</code>
   * @return The isolationWindowTarget.
   */
  @java.lang.Override
  public double getIsolationWindowTarget() {
    return isolationWindowTarget_;
  }

  public static final int UNITACCESSION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object unitAccession_ = "";
  /**
   * <pre>
   * In most of the cases will be MS:1000040 m/z
   * </pre>
   *
   * <code>string UnitAccession = 4;</code>
   * @return The unitAccession.
   */
  @java.lang.Override
  public java.lang.String getUnitAccession() {
    java.lang.Object ref = unitAccession_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      unitAccession_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * In most of the cases will be MS:1000040 m/z
   * </pre>
   *
   * <code>string UnitAccession = 4;</code>
   * @return The bytes for unitAccession.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUnitAccessionBytes() {
    java.lang.Object ref = unitAccession_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      unitAccession_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(lowerOffset_) != 0) {
      output.writeDouble(1, lowerOffset_);
    }
    if (java.lang.Double.doubleToRawLongBits(upperOffset_) != 0) {
      output.writeDouble(2, upperOffset_);
    }
    if (java.lang.Double.doubleToRawLongBits(isolationWindowTarget_) != 0) {
      output.writeDouble(3, isolationWindowTarget_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(unitAccession_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, unitAccession_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(lowerOffset_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, lowerOffset_);
    }
    if (java.lang.Double.doubleToRawLongBits(upperOffset_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, upperOffset_);
    }
    if (java.lang.Double.doubleToRawLongBits(isolationWindowTarget_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, isolationWindowTarget_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(unitAccession_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, unitAccession_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow)) {
      return super.equals(obj);
    }
    io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow other = (io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow) obj;

    if (java.lang.Double.doubleToLongBits(getLowerOffset())
        != java.lang.Double.doubleToLongBits(
            other.getLowerOffset())) return false;
    if (java.lang.Double.doubleToLongBits(getUpperOffset())
        != java.lang.Double.doubleToLongBits(
            other.getUpperOffset())) return false;
    if (java.lang.Double.doubleToLongBits(getIsolationWindowTarget())
        != java.lang.Double.doubleToLongBits(
            other.getIsolationWindowTarget())) return false;
    if (!getUnitAccession()
        .equals(other.getUnitAccession())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LOWEROFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLowerOffset()));
    hash = (37 * hash) + UPPEROFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getUpperOffset()));
    hash = (37 * hash) + ISOLATIONWINDOWTARGET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getIsolationWindowTarget()));
    hash = (37 * hash) + UNITACCESSION_FIELD_NUMBER;
    hash = (53 * hash) + getUnitAccession().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Isolation window parameter.
   * </pre>
   *
   * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.IsolationWindow}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Clearcore2.SampleData.DataAccessApi.V002.IsolationWindow)
      io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindowOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_IsolationWindow_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_IsolationWindow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow.class, io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow.Builder.class);
    }

    // Construct using io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      lowerOffset_ = 0D;
      upperOffset_ = 0D;
      isolationWindowTarget_ = 0D;
      unitAccession_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_IsolationWindow_descriptor;
    }

    @java.lang.Override
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow getDefaultInstanceForType() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow build() {
      io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow buildPartial() {
      io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow result = new io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.lowerOffset_ = lowerOffset_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.upperOffset_ = upperOffset_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.isolationWindowTarget_ = isolationWindowTarget_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.unitAccession_ = unitAccession_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow) {
        return mergeFrom((io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow other) {
      if (other == io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow.getDefaultInstance()) return this;
      if (java.lang.Double.doubleToRawLongBits(other.getLowerOffset()) != 0) {
        setLowerOffset(other.getLowerOffset());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getUpperOffset()) != 0) {
        setUpperOffset(other.getUpperOffset());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getIsolationWindowTarget()) != 0) {
        setIsolationWindowTarget(other.getIsolationWindowTarget());
      }
      if (!other.getUnitAccession().isEmpty()) {
        unitAccession_ = other.unitAccession_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              lowerOffset_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 17: {
              upperOffset_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              isolationWindowTarget_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 34: {
              unitAccession_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double lowerOffset_ ;
    /**
     * <pre>
     * The extent of the isolation window in m/z below the 
     * isolation window target m/z. The lower and upper 
     * offsets may be asymmetric about the target m/z.
     * see MS:1000828 
     * </pre>
     *
     * <code>double LowerOffset = 1;</code>
     * @return The lowerOffset.
     */
    @java.lang.Override
    public double getLowerOffset() {
      return lowerOffset_;
    }
    /**
     * <pre>
     * The extent of the isolation window in m/z below the 
     * isolation window target m/z. The lower and upper 
     * offsets may be asymmetric about the target m/z.
     * see MS:1000828 
     * </pre>
     *
     * <code>double LowerOffset = 1;</code>
     * @param value The lowerOffset to set.
     * @return This builder for chaining.
     */
    public Builder setLowerOffset(double value) {

      lowerOffset_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The extent of the isolation window in m/z below the 
     * isolation window target m/z. The lower and upper 
     * offsets may be asymmetric about the target m/z.
     * see MS:1000828 
     * </pre>
     *
     * <code>double LowerOffset = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLowerOffset() {
      bitField0_ = (bitField0_ & ~0x00000001);
      lowerOffset_ = 0D;
      onChanged();
      return this;
    }

    private double upperOffset_ ;
    /**
     * <pre>
     * The extent of the isolation window in m/z above the isolation 
     * window target m/z. The lower and upper offsets may be 
     * asymmetric about the target m/z.
     * see MS:1000829
     * </pre>
     *
     * <code>double UpperOffset = 2;</code>
     * @return The upperOffset.
     */
    @java.lang.Override
    public double getUpperOffset() {
      return upperOffset_;
    }
    /**
     * <pre>
     * The extent of the isolation window in m/z above the isolation 
     * window target m/z. The lower and upper offsets may be 
     * asymmetric about the target m/z.
     * see MS:1000829
     * </pre>
     *
     * <code>double UpperOffset = 2;</code>
     * @param value The upperOffset to set.
     * @return This builder for chaining.
     */
    public Builder setUpperOffset(double value) {

      upperOffset_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The extent of the isolation window in m/z above the isolation 
     * window target m/z. The lower and upper offsets may be 
     * asymmetric about the target m/z.
     * see MS:1000829
     * </pre>
     *
     * <code>double UpperOffset = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpperOffset() {
      bitField0_ = (bitField0_ & ~0x00000002);
      upperOffset_ = 0D;
      onChanged();
      return this;
    }

    private double isolationWindowTarget_ ;
    /**
     * <pre>
     * The primary or reference m/z about which the isolation 
     * window is defined. 
     * see  MS:1000827
     * </pre>
     *
     * <code>double IsolationWindowTarget = 3;</code>
     * @return The isolationWindowTarget.
     */
    @java.lang.Override
    public double getIsolationWindowTarget() {
      return isolationWindowTarget_;
    }
    /**
     * <pre>
     * The primary or reference m/z about which the isolation 
     * window is defined. 
     * see  MS:1000827
     * </pre>
     *
     * <code>double IsolationWindowTarget = 3;</code>
     * @param value The isolationWindowTarget to set.
     * @return This builder for chaining.
     */
    public Builder setIsolationWindowTarget(double value) {

      isolationWindowTarget_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The primary or reference m/z about which the isolation 
     * window is defined. 
     * see  MS:1000827
     * </pre>
     *
     * <code>double IsolationWindowTarget = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsolationWindowTarget() {
      bitField0_ = (bitField0_ & ~0x00000004);
      isolationWindowTarget_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object unitAccession_ = "";
    /**
     * <pre>
     * In most of the cases will be MS:1000040 m/z
     * </pre>
     *
     * <code>string UnitAccession = 4;</code>
     * @return The unitAccession.
     */
    public java.lang.String getUnitAccession() {
      java.lang.Object ref = unitAccession_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unitAccession_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * In most of the cases will be MS:1000040 m/z
     * </pre>
     *
     * <code>string UnitAccession = 4;</code>
     * @return The bytes for unitAccession.
     */
    public com.google.protobuf.ByteString
        getUnitAccessionBytes() {
      java.lang.Object ref = unitAccession_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unitAccession_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * In most of the cases will be MS:1000040 m/z
     * </pre>
     *
     * <code>string UnitAccession = 4;</code>
     * @param value The unitAccession to set.
     * @return This builder for chaining.
     */
    public Builder setUnitAccession(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      unitAccession_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * In most of the cases will be MS:1000040 m/z
     * </pre>
     *
     * <code>string UnitAccession = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnitAccession() {
      unitAccession_ = getDefaultInstance().getUnitAccession();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * In most of the cases will be MS:1000040 m/z
     * </pre>
     *
     * <code>string UnitAccession = 4;</code>
     * @param value The bytes for unitAccession to set.
     * @return This builder for chaining.
     */
    public Builder setUnitAccessionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      unitAccession_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Clearcore2.SampleData.DataAccessApi.V002.IsolationWindow)
  }

  // @@protoc_insertion_point(class_scope:Clearcore2.SampleData.DataAccessApi.V002.IsolationWindow)
  private static final io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow();
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IsolationWindow>
      PARSER = new com.google.protobuf.AbstractParser<IsolationWindow>() {
    @java.lang.Override
    public IsolationWindow parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<IsolationWindow> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IsolationWindow> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.mzmine.modules.io.import_rawdata_wiff2.api.IsolationWindow getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

