// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

@com.google.protobuf.Generated
public interface ListSamplesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Clearcore2.SampleData.DataAccessApi.V002.ListSamplesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Absolute path to the wiff file
   * </pre>
   *
   * <code>string AbsolutePathToWiffFile = 1;</code>
   * @return The absolutePathToWiffFile.
   */
  java.lang.String getAbsolutePathToWiffFile();
  /**
   * <pre>
   * Absolute path to the wiff file
   * </pre>
   *
   * <code>string AbsolutePathToWiffFile = 1;</code>
   * @return The bytes for absolutePathToWiffFile.
   */
  com.google.protobuf.ByteString
      getAbsolutePathToWiffFileBytes();

  /**
   * <pre>
   * if true then response will not include corrupted samples, if any
   * </pre>
   *
   * <code>bool SkipCorrupted = 2;</code>
   * @return The skipCorrupted.
   */
  boolean getSkipCorrupted();

  /**
   * <pre>
   * List of samples to read from the file.
   * </pre>
   *
   * <code>repeated string SampleIDs = 3;</code>
   * @return A list containing the sampleIDs.
   */
  java.util.List<java.lang.String>
      getSampleIDsList();
  /**
   * <pre>
   * List of samples to read from the file.
   * </pre>
   *
   * <code>repeated string SampleIDs = 3;</code>
   * @return The count of sampleIDs.
   */
  int getSampleIDsCount();
  /**
   * <pre>
   * List of samples to read from the file.
   * </pre>
   *
   * <code>repeated string SampleIDs = 3;</code>
   * @param index The index of the element to return.
   * @return The sampleIDs at the given index.
   */
  java.lang.String getSampleIDs(int index);
  /**
   * <pre>
   * List of samples to read from the file.
   * </pre>
   *
   * <code>repeated string SampleIDs = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the sampleIDs at the given index.
   */
  com.google.protobuf.ByteString
      getSampleIDsBytes(int index);
}
