// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

/**
 * <pre>
 * provides a list of samples
 * </pre>
 *
 * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.ListSamplesRequest}
 */
@com.google.protobuf.Generated
public final class ListSamplesRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Clearcore2.SampleData.DataAccessApi.V002.ListSamplesRequest)
    ListSamplesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "ListSamplesRequest");
  }
  // Use ListSamplesRequest.newBuilder() to construct.
  private ListSamplesRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListSamplesRequest() {
    absolutePathToWiffFile_ = "";
    sampleIDs_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_ListSamplesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_ListSamplesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest.class, io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest.Builder.class);
  }

  public static final int ABSOLUTEPATHTOWIFFFILE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object absolutePathToWiffFile_ = "";
  /**
   * <pre>
   * Absolute path to the wiff file
   * </pre>
   *
   * <code>string AbsolutePathToWiffFile = 1;</code>
   * @return The absolutePathToWiffFile.
   */
  @java.lang.Override
  public java.lang.String getAbsolutePathToWiffFile() {
    java.lang.Object ref = absolutePathToWiffFile_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      absolutePathToWiffFile_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Absolute path to the wiff file
   * </pre>
   *
   * <code>string AbsolutePathToWiffFile = 1;</code>
   * @return The bytes for absolutePathToWiffFile.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAbsolutePathToWiffFileBytes() {
    java.lang.Object ref = absolutePathToWiffFile_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      absolutePathToWiffFile_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SKIPCORRUPTED_FIELD_NUMBER = 2;
  private boolean skipCorrupted_ = false;
  /**
   * <pre>
   * if true then response will not include corrupted samples, if any
   * </pre>
   *
   * <code>bool SkipCorrupted = 2;</code>
   * @return The skipCorrupted.
   */
  @java.lang.Override
  public boolean getSkipCorrupted() {
    return skipCorrupted_;
  }

  public static final int SAMPLEIDS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList sampleIDs_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * List of samples to read from the file.
   * </pre>
   *
   * <code>repeated string SampleIDs = 3;</code>
   * @return A list containing the sampleIDs.
   */
  public com.google.protobuf.ProtocolStringList
      getSampleIDsList() {
    return sampleIDs_;
  }
  /**
   * <pre>
   * List of samples to read from the file.
   * </pre>
   *
   * <code>repeated string SampleIDs = 3;</code>
   * @return The count of sampleIDs.
   */
  public int getSampleIDsCount() {
    return sampleIDs_.size();
  }
  /**
   * <pre>
   * List of samples to read from the file.
   * </pre>
   *
   * <code>repeated string SampleIDs = 3;</code>
   * @param index The index of the element to return.
   * @return The sampleIDs at the given index.
   */
  public java.lang.String getSampleIDs(int index) {
    return sampleIDs_.get(index);
  }
  /**
   * <pre>
   * List of samples to read from the file.
   * </pre>
   *
   * <code>repeated string SampleIDs = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the sampleIDs at the given index.
   */
  public com.google.protobuf.ByteString
      getSampleIDsBytes(int index) {
    return sampleIDs_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(absolutePathToWiffFile_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, absolutePathToWiffFile_);
    }
    if (skipCorrupted_ != false) {
      output.writeBool(2, skipCorrupted_);
    }
    for (int i = 0; i < sampleIDs_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, sampleIDs_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(absolutePathToWiffFile_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, absolutePathToWiffFile_);
    }
    if (skipCorrupted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, skipCorrupted_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < sampleIDs_.size(); i++) {
        dataSize += computeStringSizeNoTag(sampleIDs_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSampleIDsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest)) {
      return super.equals(obj);
    }
    io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest other = (io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest) obj;

    if (!getAbsolutePathToWiffFile()
        .equals(other.getAbsolutePathToWiffFile())) return false;
    if (getSkipCorrupted()
        != other.getSkipCorrupted()) return false;
    if (!getSampleIDsList()
        .equals(other.getSampleIDsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ABSOLUTEPATHTOWIFFFILE_FIELD_NUMBER;
    hash = (53 * hash) + getAbsolutePathToWiffFile().hashCode();
    hash = (37 * hash) + SKIPCORRUPTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSkipCorrupted());
    if (getSampleIDsCount() > 0) {
      hash = (37 * hash) + SAMPLEIDS_FIELD_NUMBER;
      hash = (53 * hash) + getSampleIDsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * provides a list of samples
   * </pre>
   *
   * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.ListSamplesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Clearcore2.SampleData.DataAccessApi.V002.ListSamplesRequest)
      io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_ListSamplesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_ListSamplesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest.class, io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest.Builder.class);
    }

    // Construct using io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      absolutePathToWiffFile_ = "";
      skipCorrupted_ = false;
      sampleIDs_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_ListSamplesRequest_descriptor;
    }

    @java.lang.Override
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest getDefaultInstanceForType() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest build() {
      io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest buildPartial() {
      io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest result = new io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.absolutePathToWiffFile_ = absolutePathToWiffFile_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.skipCorrupted_ = skipCorrupted_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        sampleIDs_.makeImmutable();
        result.sampleIDs_ = sampleIDs_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest) {
        return mergeFrom((io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest other) {
      if (other == io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest.getDefaultInstance()) return this;
      if (!other.getAbsolutePathToWiffFile().isEmpty()) {
        absolutePathToWiffFile_ = other.absolutePathToWiffFile_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getSkipCorrupted() != false) {
        setSkipCorrupted(other.getSkipCorrupted());
      }
      if (!other.sampleIDs_.isEmpty()) {
        if (sampleIDs_.isEmpty()) {
          sampleIDs_ = other.sampleIDs_;
          bitField0_ |= 0x00000004;
        } else {
          ensureSampleIDsIsMutable();
          sampleIDs_.addAll(other.sampleIDs_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              absolutePathToWiffFile_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              skipCorrupted_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureSampleIDsIsMutable();
              sampleIDs_.add(s);
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object absolutePathToWiffFile_ = "";
    /**
     * <pre>
     * Absolute path to the wiff file
     * </pre>
     *
     * <code>string AbsolutePathToWiffFile = 1;</code>
     * @return The absolutePathToWiffFile.
     */
    public java.lang.String getAbsolutePathToWiffFile() {
      java.lang.Object ref = absolutePathToWiffFile_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        absolutePathToWiffFile_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Absolute path to the wiff file
     * </pre>
     *
     * <code>string AbsolutePathToWiffFile = 1;</code>
     * @return The bytes for absolutePathToWiffFile.
     */
    public com.google.protobuf.ByteString
        getAbsolutePathToWiffFileBytes() {
      java.lang.Object ref = absolutePathToWiffFile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        absolutePathToWiffFile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Absolute path to the wiff file
     * </pre>
     *
     * <code>string AbsolutePathToWiffFile = 1;</code>
     * @param value The absolutePathToWiffFile to set.
     * @return This builder for chaining.
     */
    public Builder setAbsolutePathToWiffFile(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      absolutePathToWiffFile_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Absolute path to the wiff file
     * </pre>
     *
     * <code>string AbsolutePathToWiffFile = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAbsolutePathToWiffFile() {
      absolutePathToWiffFile_ = getDefaultInstance().getAbsolutePathToWiffFile();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Absolute path to the wiff file
     * </pre>
     *
     * <code>string AbsolutePathToWiffFile = 1;</code>
     * @param value The bytes for absolutePathToWiffFile to set.
     * @return This builder for chaining.
     */
    public Builder setAbsolutePathToWiffFileBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      absolutePathToWiffFile_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean skipCorrupted_ ;
    /**
     * <pre>
     * if true then response will not include corrupted samples, if any
     * </pre>
     *
     * <code>bool SkipCorrupted = 2;</code>
     * @return The skipCorrupted.
     */
    @java.lang.Override
    public boolean getSkipCorrupted() {
      return skipCorrupted_;
    }
    /**
     * <pre>
     * if true then response will not include corrupted samples, if any
     * </pre>
     *
     * <code>bool SkipCorrupted = 2;</code>
     * @param value The skipCorrupted to set.
     * @return This builder for chaining.
     */
    public Builder setSkipCorrupted(boolean value) {

      skipCorrupted_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * if true then response will not include corrupted samples, if any
     * </pre>
     *
     * <code>bool SkipCorrupted = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSkipCorrupted() {
      bitField0_ = (bitField0_ & ~0x00000002);
      skipCorrupted_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList sampleIDs_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureSampleIDsIsMutable() {
      if (!sampleIDs_.isModifiable()) {
        sampleIDs_ = new com.google.protobuf.LazyStringArrayList(sampleIDs_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <pre>
     * List of samples to read from the file.
     * </pre>
     *
     * <code>repeated string SampleIDs = 3;</code>
     * @return A list containing the sampleIDs.
     */
    public com.google.protobuf.ProtocolStringList
        getSampleIDsList() {
      sampleIDs_.makeImmutable();
      return sampleIDs_;
    }
    /**
     * <pre>
     * List of samples to read from the file.
     * </pre>
     *
     * <code>repeated string SampleIDs = 3;</code>
     * @return The count of sampleIDs.
     */
    public int getSampleIDsCount() {
      return sampleIDs_.size();
    }
    /**
     * <pre>
     * List of samples to read from the file.
     * </pre>
     *
     * <code>repeated string SampleIDs = 3;</code>
     * @param index The index of the element to return.
     * @return The sampleIDs at the given index.
     */
    public java.lang.String getSampleIDs(int index) {
      return sampleIDs_.get(index);
    }
    /**
     * <pre>
     * List of samples to read from the file.
     * </pre>
     *
     * <code>repeated string SampleIDs = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the sampleIDs at the given index.
     */
    public com.google.protobuf.ByteString
        getSampleIDsBytes(int index) {
      return sampleIDs_.getByteString(index);
    }
    /**
     * <pre>
     * List of samples to read from the file.
     * </pre>
     *
     * <code>repeated string SampleIDs = 3;</code>
     * @param index The index to set the value at.
     * @param value The sampleIDs to set.
     * @return This builder for chaining.
     */
    public Builder setSampleIDs(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureSampleIDsIsMutable();
      sampleIDs_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of samples to read from the file.
     * </pre>
     *
     * <code>repeated string SampleIDs = 3;</code>
     * @param value The sampleIDs to add.
     * @return This builder for chaining.
     */
    public Builder addSampleIDs(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureSampleIDsIsMutable();
      sampleIDs_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of samples to read from the file.
     * </pre>
     *
     * <code>repeated string SampleIDs = 3;</code>
     * @param values The sampleIDs to add.
     * @return This builder for chaining.
     */
    public Builder addAllSampleIDs(
        java.lang.Iterable<java.lang.String> values) {
      ensureSampleIDsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, sampleIDs_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of samples to read from the file.
     * </pre>
     *
     * <code>repeated string SampleIDs = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSampleIDs() {
      sampleIDs_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of samples to read from the file.
     * </pre>
     *
     * <code>repeated string SampleIDs = 3;</code>
     * @param value The bytes of the sampleIDs to add.
     * @return This builder for chaining.
     */
    public Builder addSampleIDsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureSampleIDsIsMutable();
      sampleIDs_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Clearcore2.SampleData.DataAccessApi.V002.ListSamplesRequest)
  }

  // @@protoc_insertion_point(class_scope:Clearcore2.SampleData.DataAccessApi.V002.ListSamplesRequest)
  private static final io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest();
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListSamplesRequest>
      PARSER = new com.google.protobuf.AbstractParser<ListSamplesRequest>() {
    @java.lang.Override
    public ListSamplesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListSamplesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListSamplesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.mzmine.modules.io.import_rawdata_wiff2.api.ListSamplesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

