// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

@com.google.protobuf.Generated
public interface MsMethodExperimentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * returns name of the parameter
   * </pre>
   *
   * <code>string Name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <pre>
   * returns name of the parameter
   * </pre>
   *
   * <code>string Name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * returns the parameters for this experiment
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 2;</code>
   */
  java.util.List<Parameter>
      getParametersList();
  /**
   * <pre>
   * returns the parameters for this experiment
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 2;</code>
   */
  Parameter getParameters(int index);
  /**
   * <pre>
   * returns the parameters for this experiment
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 2;</code>
   */
  int getParametersCount();
  /**
   * <pre>
   * returns the parameters for this experiment
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 2;</code>
   */
  java.util.List<? extends ParameterOrBuilder>
      getParametersOrBuilderList();
  /**
   * <pre>
   * returns the parameters for this experiment
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 2;</code>
   */
  ParameterOrBuilder getParametersOrBuilder(
      int index);

  /**
   * <pre>
   * returns the sub experiments for this experiment
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 3;</code>
   */
  java.util.List<MsMethodExperiment>
      getExperimentsList();
  /**
   * <pre>
   * returns the sub experiments for this experiment
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 3;</code>
   */
  MsMethodExperiment getExperiments(int index);
  /**
   * <pre>
   * returns the sub experiments for this experiment
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 3;</code>
   */
  int getExperimentsCount();
  /**
   * <pre>
   * returns the sub experiments for this experiment
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 3;</code>
   */
  java.util.List<? extends MsMethodExperimentOrBuilder>
      getExperimentsOrBuilderList();
  /**
   * <pre>
   * returns the sub experiments for this experiment
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 3;</code>
   */
  MsMethodExperimentOrBuilder getExperimentsOrBuilder(
      int index);
}
