// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

/**
 * <pre>
 * MsMethod information
 * </pre>
 *
 * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.MsMethod}
 */
@com.google.protobuf.Generated
public final class MsMethod extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Clearcore2.SampleData.DataAccessApi.V002.MsMethod)
    MsMethodOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "MsMethod");
  }
  // Use MsMethod.newBuilder() to construct.
  private MsMethod(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MsMethod() {
    sourceParameters_ = java.util.Collections.emptyList();
    experiments_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_MsMethod_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_MsMethod_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod.class, io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod.Builder.class);
  }

  public static final int SOURCEPARAMETERS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter> sourceParameters_;
  /**
   * <pre>
   * returns the source Parameters
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter> getSourceParametersList() {
    return sourceParameters_;
  }
  /**
   * <pre>
   * returns the source Parameters
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.github.mzmine.modules.io.import_rawdata_wiff2.api.ParameterOrBuilder> 
      getSourceParametersOrBuilderList() {
    return sourceParameters_;
  }
  /**
   * <pre>
   * returns the source Parameters
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
   */
  @java.lang.Override
  public int getSourceParametersCount() {
    return sourceParameters_.size();
  }
  /**
   * <pre>
   * returns the source Parameters
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
   */
  @java.lang.Override
  public io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter getSourceParameters(int index) {
    return sourceParameters_.get(index);
  }
  /**
   * <pre>
   * returns the source Parameters
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
   */
  @java.lang.Override
  public io.github.mzmine.modules.io.import_rawdata_wiff2.api.ParameterOrBuilder getSourceParametersOrBuilder(
      int index) {
    return sourceParameters_.get(index);
  }

  public static final int EXPERIMENTS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment> experiments_;
  /**
   * <pre>
   * returns the experiment information 
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
   */
  @java.lang.Override
  public java.util.List<io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment> getExperimentsList() {
    return experiments_;
  }
  /**
   * <pre>
   * returns the experiment information 
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperimentOrBuilder> 
      getExperimentsOrBuilderList() {
    return experiments_;
  }
  /**
   * <pre>
   * returns the experiment information 
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
   */
  @java.lang.Override
  public int getExperimentsCount() {
    return experiments_.size();
  }
  /**
   * <pre>
   * returns the experiment information 
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
   */
  @java.lang.Override
  public io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment getExperiments(int index) {
    return experiments_.get(index);
  }
  /**
   * <pre>
   * returns the experiment information 
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
   */
  @java.lang.Override
  public io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperimentOrBuilder getExperimentsOrBuilder(
      int index) {
    return experiments_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < sourceParameters_.size(); i++) {
      output.writeMessage(1, sourceParameters_.get(i));
    }
    for (int i = 0; i < experiments_.size(); i++) {
      output.writeMessage(2, experiments_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < sourceParameters_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, sourceParameters_.get(i));
    }
    for (int i = 0; i < experiments_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, experiments_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod)) {
      return super.equals(obj);
    }
    io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod other = (io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod) obj;

    if (!getSourceParametersList()
        .equals(other.getSourceParametersList())) return false;
    if (!getExperimentsList()
        .equals(other.getExperimentsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSourceParametersCount() > 0) {
      hash = (37 * hash) + SOURCEPARAMETERS_FIELD_NUMBER;
      hash = (53 * hash) + getSourceParametersList().hashCode();
    }
    if (getExperimentsCount() > 0) {
      hash = (37 * hash) + EXPERIMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getExperimentsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * MsMethod information
   * </pre>
   *
   * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.MsMethod}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Clearcore2.SampleData.DataAccessApi.V002.MsMethod)
      io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_MsMethod_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_MsMethod_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod.class, io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod.Builder.class);
    }

    // Construct using io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (sourceParametersBuilder_ == null) {
        sourceParameters_ = java.util.Collections.emptyList();
      } else {
        sourceParameters_ = null;
        sourceParametersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (experimentsBuilder_ == null) {
        experiments_ = java.util.Collections.emptyList();
      } else {
        experiments_ = null;
        experimentsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_MsMethod_descriptor;
    }

    @java.lang.Override
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod getDefaultInstanceForType() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod build() {
      io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod buildPartial() {
      io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod result = new io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod result) {
      if (sourceParametersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          sourceParameters_ = java.util.Collections.unmodifiableList(sourceParameters_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.sourceParameters_ = sourceParameters_;
      } else {
        result.sourceParameters_ = sourceParametersBuilder_.build();
      }
      if (experimentsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          experiments_ = java.util.Collections.unmodifiableList(experiments_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.experiments_ = experiments_;
      } else {
        result.experiments_ = experimentsBuilder_.build();
      }
    }

    private void buildPartial0(io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod) {
        return mergeFrom((io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod other) {
      if (other == io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod.getDefaultInstance()) return this;
      if (sourceParametersBuilder_ == null) {
        if (!other.sourceParameters_.isEmpty()) {
          if (sourceParameters_.isEmpty()) {
            sourceParameters_ = other.sourceParameters_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSourceParametersIsMutable();
            sourceParameters_.addAll(other.sourceParameters_);
          }
          onChanged();
        }
      } else {
        if (!other.sourceParameters_.isEmpty()) {
          if (sourceParametersBuilder_.isEmpty()) {
            sourceParametersBuilder_.dispose();
            sourceParametersBuilder_ = null;
            sourceParameters_ = other.sourceParameters_;
            bitField0_ = (bitField0_ & ~0x00000001);
            sourceParametersBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetSourceParametersFieldBuilder() : null;
          } else {
            sourceParametersBuilder_.addAllMessages(other.sourceParameters_);
          }
        }
      }
      if (experimentsBuilder_ == null) {
        if (!other.experiments_.isEmpty()) {
          if (experiments_.isEmpty()) {
            experiments_ = other.experiments_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureExperimentsIsMutable();
            experiments_.addAll(other.experiments_);
          }
          onChanged();
        }
      } else {
        if (!other.experiments_.isEmpty()) {
          if (experimentsBuilder_.isEmpty()) {
            experimentsBuilder_.dispose();
            experimentsBuilder_ = null;
            experiments_ = other.experiments_;
            bitField0_ = (bitField0_ & ~0x00000002);
            experimentsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetExperimentsFieldBuilder() : null;
          } else {
            experimentsBuilder_.addAllMessages(other.experiments_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter m =
                  input.readMessage(
                      io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter.parser(),
                      extensionRegistry);
              if (sourceParametersBuilder_ == null) {
                ensureSourceParametersIsMutable();
                sourceParameters_.add(m);
              } else {
                sourceParametersBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment m =
                  input.readMessage(
                      io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment.parser(),
                      extensionRegistry);
              if (experimentsBuilder_ == null) {
                ensureExperimentsIsMutable();
                experiments_.add(m);
              } else {
                experimentsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter> sourceParameters_ =
      java.util.Collections.emptyList();
    private void ensureSourceParametersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        sourceParameters_ = new java.util.ArrayList<io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter>(sourceParameters_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter, io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter.Builder, io.github.mzmine.modules.io.import_rawdata_wiff2.api.ParameterOrBuilder> sourceParametersBuilder_;

    /**
     * <pre>
     * returns the source Parameters
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
     */
    public java.util.List<io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter> getSourceParametersList() {
      if (sourceParametersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(sourceParameters_);
      } else {
        return sourceParametersBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * returns the source Parameters
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
     */
    public int getSourceParametersCount() {
      if (sourceParametersBuilder_ == null) {
        return sourceParameters_.size();
      } else {
        return sourceParametersBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * returns the source Parameters
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter getSourceParameters(int index) {
      if (sourceParametersBuilder_ == null) {
        return sourceParameters_.get(index);
      } else {
        return sourceParametersBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * returns the source Parameters
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
     */
    public Builder setSourceParameters(
        int index, io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter value) {
      if (sourceParametersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSourceParametersIsMutable();
        sourceParameters_.set(index, value);
        onChanged();
      } else {
        sourceParametersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * returns the source Parameters
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
     */
    public Builder setSourceParameters(
        int index, io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter.Builder builderForValue) {
      if (sourceParametersBuilder_ == null) {
        ensureSourceParametersIsMutable();
        sourceParameters_.set(index, builderForValue.build());
        onChanged();
      } else {
        sourceParametersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * returns the source Parameters
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
     */
    public Builder addSourceParameters(io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter value) {
      if (sourceParametersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSourceParametersIsMutable();
        sourceParameters_.add(value);
        onChanged();
      } else {
        sourceParametersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * returns the source Parameters
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
     */
    public Builder addSourceParameters(
        int index, io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter value) {
      if (sourceParametersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSourceParametersIsMutable();
        sourceParameters_.add(index, value);
        onChanged();
      } else {
        sourceParametersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * returns the source Parameters
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
     */
    public Builder addSourceParameters(
        io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter.Builder builderForValue) {
      if (sourceParametersBuilder_ == null) {
        ensureSourceParametersIsMutable();
        sourceParameters_.add(builderForValue.build());
        onChanged();
      } else {
        sourceParametersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * returns the source Parameters
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
     */
    public Builder addSourceParameters(
        int index, io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter.Builder builderForValue) {
      if (sourceParametersBuilder_ == null) {
        ensureSourceParametersIsMutable();
        sourceParameters_.add(index, builderForValue.build());
        onChanged();
      } else {
        sourceParametersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * returns the source Parameters
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
     */
    public Builder addAllSourceParameters(
        java.lang.Iterable<? extends io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter> values) {
      if (sourceParametersBuilder_ == null) {
        ensureSourceParametersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sourceParameters_);
        onChanged();
      } else {
        sourceParametersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * returns the source Parameters
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
     */
    public Builder clearSourceParameters() {
      if (sourceParametersBuilder_ == null) {
        sourceParameters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        sourceParametersBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * returns the source Parameters
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
     */
    public Builder removeSourceParameters(int index) {
      if (sourceParametersBuilder_ == null) {
        ensureSourceParametersIsMutable();
        sourceParameters_.remove(index);
        onChanged();
      } else {
        sourceParametersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * returns the source Parameters
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter.Builder getSourceParametersBuilder(
        int index) {
      return internalGetSourceParametersFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * returns the source Parameters
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.ParameterOrBuilder getSourceParametersOrBuilder(
        int index) {
      if (sourceParametersBuilder_ == null) {
        return sourceParameters_.get(index);  } else {
        return sourceParametersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * returns the source Parameters
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
     */
    public java.util.List<? extends io.github.mzmine.modules.io.import_rawdata_wiff2.api.ParameterOrBuilder> 
         getSourceParametersOrBuilderList() {
      if (sourceParametersBuilder_ != null) {
        return sourceParametersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(sourceParameters_);
      }
    }
    /**
     * <pre>
     * returns the source Parameters
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter.Builder addSourceParametersBuilder() {
      return internalGetSourceParametersFieldBuilder().addBuilder(
          io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter.getDefaultInstance());
    }
    /**
     * <pre>
     * returns the source Parameters
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter.Builder addSourceParametersBuilder(
        int index) {
      return internalGetSourceParametersFieldBuilder().addBuilder(
          index, io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter.getDefaultInstance());
    }
    /**
     * <pre>
     * returns the source Parameters
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter SourceParameters = 1;</code>
     */
    public java.util.List<io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter.Builder> 
         getSourceParametersBuilderList() {
      return internalGetSourceParametersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter, io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter.Builder, io.github.mzmine.modules.io.import_rawdata_wiff2.api.ParameterOrBuilder> 
        internalGetSourceParametersFieldBuilder() {
      if (sourceParametersBuilder_ == null) {
        sourceParametersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter, io.github.mzmine.modules.io.import_rawdata_wiff2.api.Parameter.Builder, io.github.mzmine.modules.io.import_rawdata_wiff2.api.ParameterOrBuilder>(
                sourceParameters_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        sourceParameters_ = null;
      }
      return sourceParametersBuilder_;
    }

    private java.util.List<io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment> experiments_ =
      java.util.Collections.emptyList();
    private void ensureExperimentsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        experiments_ = new java.util.ArrayList<io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment>(experiments_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment, io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment.Builder, io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperimentOrBuilder> experimentsBuilder_;

    /**
     * <pre>
     * returns the experiment information 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
     */
    public java.util.List<io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment> getExperimentsList() {
      if (experimentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(experiments_);
      } else {
        return experimentsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * returns the experiment information 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
     */
    public int getExperimentsCount() {
      if (experimentsBuilder_ == null) {
        return experiments_.size();
      } else {
        return experimentsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * returns the experiment information 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment getExperiments(int index) {
      if (experimentsBuilder_ == null) {
        return experiments_.get(index);
      } else {
        return experimentsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * returns the experiment information 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
     */
    public Builder setExperiments(
        int index, io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment value) {
      if (experimentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExperimentsIsMutable();
        experiments_.set(index, value);
        onChanged();
      } else {
        experimentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * returns the experiment information 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
     */
    public Builder setExperiments(
        int index, io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment.Builder builderForValue) {
      if (experimentsBuilder_ == null) {
        ensureExperimentsIsMutable();
        experiments_.set(index, builderForValue.build());
        onChanged();
      } else {
        experimentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * returns the experiment information 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
     */
    public Builder addExperiments(io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment value) {
      if (experimentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExperimentsIsMutable();
        experiments_.add(value);
        onChanged();
      } else {
        experimentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * returns the experiment information 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
     */
    public Builder addExperiments(
        int index, io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment value) {
      if (experimentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExperimentsIsMutable();
        experiments_.add(index, value);
        onChanged();
      } else {
        experimentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * returns the experiment information 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
     */
    public Builder addExperiments(
        io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment.Builder builderForValue) {
      if (experimentsBuilder_ == null) {
        ensureExperimentsIsMutable();
        experiments_.add(builderForValue.build());
        onChanged();
      } else {
        experimentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * returns the experiment information 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
     */
    public Builder addExperiments(
        int index, io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment.Builder builderForValue) {
      if (experimentsBuilder_ == null) {
        ensureExperimentsIsMutable();
        experiments_.add(index, builderForValue.build());
        onChanged();
      } else {
        experimentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * returns the experiment information 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
     */
    public Builder addAllExperiments(
        java.lang.Iterable<? extends io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment> values) {
      if (experimentsBuilder_ == null) {
        ensureExperimentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, experiments_);
        onChanged();
      } else {
        experimentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * returns the experiment information 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
     */
    public Builder clearExperiments() {
      if (experimentsBuilder_ == null) {
        experiments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        experimentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * returns the experiment information 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
     */
    public Builder removeExperiments(int index) {
      if (experimentsBuilder_ == null) {
        ensureExperimentsIsMutable();
        experiments_.remove(index);
        onChanged();
      } else {
        experimentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * returns the experiment information 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment.Builder getExperimentsBuilder(
        int index) {
      return internalGetExperimentsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * returns the experiment information 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperimentOrBuilder getExperimentsOrBuilder(
        int index) {
      if (experimentsBuilder_ == null) {
        return experiments_.get(index);  } else {
        return experimentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * returns the experiment information 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
     */
    public java.util.List<? extends io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperimentOrBuilder> 
         getExperimentsOrBuilderList() {
      if (experimentsBuilder_ != null) {
        return experimentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(experiments_);
      }
    }
    /**
     * <pre>
     * returns the experiment information 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment.Builder addExperimentsBuilder() {
      return internalGetExperimentsFieldBuilder().addBuilder(
          io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment.getDefaultInstance());
    }
    /**
     * <pre>
     * returns the experiment information 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment.Builder addExperimentsBuilder(
        int index) {
      return internalGetExperimentsFieldBuilder().addBuilder(
          index, io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment.getDefaultInstance());
    }
    /**
     * <pre>
     * returns the experiment information 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 2;</code>
     */
    public java.util.List<io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment.Builder> 
         getExperimentsBuilderList() {
      return internalGetExperimentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment, io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment.Builder, io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperimentOrBuilder> 
        internalGetExperimentsFieldBuilder() {
      if (experimentsBuilder_ == null) {
        experimentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment, io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment.Builder, io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperimentOrBuilder>(
                experiments_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        experiments_ = null;
      }
      return experimentsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:Clearcore2.SampleData.DataAccessApi.V002.MsMethod)
  }

  // @@protoc_insertion_point(class_scope:Clearcore2.SampleData.DataAccessApi.V002.MsMethod)
  private static final io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod();
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MsMethod>
      PARSER = new com.google.protobuf.AbstractParser<MsMethod>() {
    @java.lang.Override
    public MsMethod parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MsMethod> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MsMethod> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethod getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

