// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

@com.google.protobuf.Generated
public interface ParagraphOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Clearcore2.SampleData.DataAccessApi.V002.Paragraph)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Paragraph name.
   * </pre>
   *
   * <code>string Name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <pre>
   * Paragraph name.
   * </pre>
   *
   * <code>string Name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Gets the list of parameters.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 2;</code>
   */
  java.util.List<Parameter>
      getParametersList();
  /**
   * <pre>
   * Gets the list of parameters.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 2;</code>
   */
  Parameter getParameters(int index);
  /**
   * <pre>
   * Gets the list of parameters.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 2;</code>
   */
  int getParametersCount();
  /**
   * <pre>
   * Gets the list of parameters.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 2;</code>
   */
  java.util.List<? extends ParameterOrBuilder>
      getParametersOrBuilderList();
  /**
   * <pre>
   * Gets the list of parameters.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 2;</code>
   */
  ParameterOrBuilder getParametersOrBuilder(
      int index);

  /**
   * <pre>
   * Get the table Parameters.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Table Tables = 3;</code>
   */
  java.util.List<Table>
      getTablesList();
  /**
   * <pre>
   * Get the table Parameters.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Table Tables = 3;</code>
   */
  Table getTables(int index);
  /**
   * <pre>
   * Get the table Parameters.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Table Tables = 3;</code>
   */
  int getTablesCount();
  /**
   * <pre>
   * Get the table Parameters.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Table Tables = 3;</code>
   */
  java.util.List<? extends TableOrBuilder>
      getTablesOrBuilderList();
  /**
   * <pre>
   * Get the table Parameters.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Table Tables = 3;</code>
   */
  TableOrBuilder getTablesOrBuilder(
      int index);
}
