// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

@com.google.protobuf.Generated
public interface ScanRecordInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Clearcore2.SampleData.DataAccessApi.V002.ScanRecordInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * offset relative to the start of the binary scan file. Only valid when length is not 0.
   * </pre>
   *
   * <code>int64 Offset = 1;</code>
   * @return The offset.
   */
  long getOffset();

  /**
   * <pre>
   * length of the data. If the data length is 0 then the record should not be used for reading.
   * </pre>
   *
   * <code>int32 Length = 2;</code>
   * @return The length.
   */
  int getLength();

  /**
   * <pre>
   * Must be present for Tof scan and will be NULL for Non-Tof Scans
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TofCalibrationParameters TofCalibration = 3;</code>
   * @return Whether the tofCalibration field is set.
   */
  boolean hasTofCalibration();
  /**
   * <pre>
   * Must be present for Tof scan and will be NULL for Non-Tof Scans
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TofCalibrationParameters TofCalibration = 3;</code>
   * @return The tofCalibration.
   */
  io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofCalibrationParameters getTofCalibration();
  /**
   * <pre>
   * Must be present for Tof scan and will be NULL for Non-Tof Scans
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TofCalibrationParameters TofCalibration = 3;</code>
   */
  io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofCalibrationParametersOrBuilder getTofCalibrationOrBuilder();

  /**
   * <pre>
   * Precursor Mass encapsulates ParentMz and ParentChargeState
   * </pre>
   *
   * <code>double PrecursorMass = 4;</code>
   * @return The precursorMass.
   */
  double getPrecursorMass();

  /**
   * <pre>
   * retention time of this scan
   * </pre>
   *
   * <code>double RetentionTime = 5;</code>
   * @return The retentionTime.
   */
  double getRetentionTime();
}
