// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

/**
 * <pre>
 * m/z bounds of a mass spectrometer scan window
 * </pre>
 *
 * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.ScanWindow}
 */
@com.google.protobuf.Generated
public final class ScanWindow extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Clearcore2.SampleData.DataAccessApi.V002.ScanWindow)
    ScanWindowOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "ScanWindow");
  }
  // Use ScanWindow.newBuilder() to construct.
  private ScanWindow(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ScanWindow() {
    unitAccession_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_ScanWindow_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_ScanWindow_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow.class, io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow.Builder.class);
  }

  public static final int START_FIELD_NUMBER = 1;
  private double start_ = 0D;
  /**
   * <pre>
   * Scan window lower limit
   * see MS:1000501 for details
   * </pre>
   *
   * <code>double Start = 1;</code>
   * @return The start.
   */
  @java.lang.Override
  public double getStart() {
    return start_;
  }

  public static final int END_FIELD_NUMBER = 2;
  private double end_ = 0D;
  /**
   * <pre>
   * Scan window upper limit
   * see MS:1000500 for details
   * </pre>
   *
   * <code>double End = 2;</code>
   * @return The end.
   */
  @java.lang.Override
  public double getEnd() {
    return end_;
  }

  public static final int UNITACCESSION_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object unitAccession_ = "";
  /**
   * <pre>
   * In most of the cases will be MS:1000040
   * </pre>
   *
   * <code>string UnitAccession = 3;</code>
   * @return The unitAccession.
   */
  @java.lang.Override
  public java.lang.String getUnitAccession() {
    java.lang.Object ref = unitAccession_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      unitAccession_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * In most of the cases will be MS:1000040
   * </pre>
   *
   * <code>string UnitAccession = 3;</code>
   * @return The bytes for unitAccession.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUnitAccessionBytes() {
    java.lang.Object ref = unitAccession_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      unitAccession_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(start_) != 0) {
      output.writeDouble(1, start_);
    }
    if (java.lang.Double.doubleToRawLongBits(end_) != 0) {
      output.writeDouble(2, end_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(unitAccession_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, unitAccession_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(start_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, start_);
    }
    if (java.lang.Double.doubleToRawLongBits(end_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, end_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(unitAccession_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, unitAccession_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow)) {
      return super.equals(obj);
    }
    io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow other = (io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow) obj;

    if (java.lang.Double.doubleToLongBits(getStart())
        != java.lang.Double.doubleToLongBits(
            other.getStart())) return false;
    if (java.lang.Double.doubleToLongBits(getEnd())
        != java.lang.Double.doubleToLongBits(
            other.getEnd())) return false;
    if (!getUnitAccession()
        .equals(other.getUnitAccession())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + START_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getStart()));
    hash = (37 * hash) + END_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getEnd()));
    hash = (37 * hash) + UNITACCESSION_FIELD_NUMBER;
    hash = (53 * hash) + getUnitAccession().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * m/z bounds of a mass spectrometer scan window
   * </pre>
   *
   * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.ScanWindow}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Clearcore2.SampleData.DataAccessApi.V002.ScanWindow)
      io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindowOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_ScanWindow_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_ScanWindow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow.class, io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow.Builder.class);
    }

    // Construct using io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      start_ = 0D;
      end_ = 0D;
      unitAccession_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_ScanWindow_descriptor;
    }

    @java.lang.Override
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow getDefaultInstanceForType() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow build() {
      io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow buildPartial() {
      io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow result = new io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.start_ = start_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.end_ = end_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.unitAccession_ = unitAccession_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow) {
        return mergeFrom((io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow other) {
      if (other == io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow.getDefaultInstance()) return this;
      if (java.lang.Double.doubleToRawLongBits(other.getStart()) != 0) {
        setStart(other.getStart());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getEnd()) != 0) {
        setEnd(other.getEnd());
      }
      if (!other.getUnitAccession().isEmpty()) {
        unitAccession_ = other.unitAccession_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              start_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 17: {
              end_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 26: {
              unitAccession_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double start_ ;
    /**
     * <pre>
     * Scan window lower limit
     * see MS:1000501 for details
     * </pre>
     *
     * <code>double Start = 1;</code>
     * @return The start.
     */
    @java.lang.Override
    public double getStart() {
      return start_;
    }
    /**
     * <pre>
     * Scan window lower limit
     * see MS:1000501 for details
     * </pre>
     *
     * <code>double Start = 1;</code>
     * @param value The start to set.
     * @return This builder for chaining.
     */
    public Builder setStart(double value) {

      start_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Scan window lower limit
     * see MS:1000501 for details
     * </pre>
     *
     * <code>double Start = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStart() {
      bitField0_ = (bitField0_ & ~0x00000001);
      start_ = 0D;
      onChanged();
      return this;
    }

    private double end_ ;
    /**
     * <pre>
     * Scan window upper limit
     * see MS:1000500 for details
     * </pre>
     *
     * <code>double End = 2;</code>
     * @return The end.
     */
    @java.lang.Override
    public double getEnd() {
      return end_;
    }
    /**
     * <pre>
     * Scan window upper limit
     * see MS:1000500 for details
     * </pre>
     *
     * <code>double End = 2;</code>
     * @param value The end to set.
     * @return This builder for chaining.
     */
    public Builder setEnd(double value) {

      end_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Scan window upper limit
     * see MS:1000500 for details
     * </pre>
     *
     * <code>double End = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnd() {
      bitField0_ = (bitField0_ & ~0x00000002);
      end_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object unitAccession_ = "";
    /**
     * <pre>
     * In most of the cases will be MS:1000040
     * </pre>
     *
     * <code>string UnitAccession = 3;</code>
     * @return The unitAccession.
     */
    public java.lang.String getUnitAccession() {
      java.lang.Object ref = unitAccession_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unitAccession_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * In most of the cases will be MS:1000040
     * </pre>
     *
     * <code>string UnitAccession = 3;</code>
     * @return The bytes for unitAccession.
     */
    public com.google.protobuf.ByteString
        getUnitAccessionBytes() {
      java.lang.Object ref = unitAccession_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unitAccession_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * In most of the cases will be MS:1000040
     * </pre>
     *
     * <code>string UnitAccession = 3;</code>
     * @param value The unitAccession to set.
     * @return This builder for chaining.
     */
    public Builder setUnitAccession(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      unitAccession_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * In most of the cases will be MS:1000040
     * </pre>
     *
     * <code>string UnitAccession = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnitAccession() {
      unitAccession_ = getDefaultInstance().getUnitAccession();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * In most of the cases will be MS:1000040
     * </pre>
     *
     * <code>string UnitAccession = 3;</code>
     * @param value The bytes for unitAccession to set.
     * @return This builder for chaining.
     */
    public Builder setUnitAccessionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      unitAccession_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Clearcore2.SampleData.DataAccessApi.V002.ScanWindow)
  }

  // @@protoc_insertion_point(class_scope:Clearcore2.SampleData.DataAccessApi.V002.ScanWindow)
  private static final io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow();
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ScanWindow>
      PARSER = new com.google.protobuf.AbstractParser<ScanWindow>() {
    @java.lang.Override
    public ScanWindow parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ScanWindow> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ScanWindow> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.mzmine.modules.io.import_rawdata_wiff2.api.ScanWindow getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

