// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

/**
 * <pre>
 * The structure that captures the generation of a peak list 
 * (including the underlying acquisitions). Also describes some 
 * of the parameters for the mass spectrometer for a given 
 * acquisition (or list of acquisitions).
 * </pre>
 *
 * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.Spectrum}
 */
@com.google.protobuf.Generated
public final class Spectrum extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Clearcore2.SampleData.DataAccessApi.V002.Spectrum)
    SpectrumOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "Spectrum");
  }
  // Use Spectrum.newBuilder() to construct.
  private Spectrum(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Spectrum() {
    id_ = "";
    experimentId_ = "";
    sampleId_ = "";
    data_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_Spectrum_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_Spectrum_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum.class, io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <pre>
   * the Id of the spectrum
   * </pre>
   *
   * <code>string Id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * the Id of the spectrum
   * </pre>
   *
   * <code>string Id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPERIMENTID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object experimentId_ = "";
  /**
   * <pre>
   * The id of the experiment used to acquire this spectrum
   * </pre>
   *
   * <code>string ExperimentId = 2;</code>
   * @return The experimentId.
   */
  @java.lang.Override
  public java.lang.String getExperimentId() {
    java.lang.Object ref = experimentId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      experimentId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The id of the experiment used to acquire this spectrum
   * </pre>
   *
   * <code>string ExperimentId = 2;</code>
   * @return The bytes for experimentId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExperimentIdBytes() {
    java.lang.Object ref = experimentId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      experimentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SAMPLEID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sampleId_ = "";
  /**
   * <pre>
   * The sample identifier 
   * </pre>
   *
   * <code>string SampleId = 3;</code>
   * @return The sampleId.
   */
  @java.lang.Override
  public java.lang.String getSampleId() {
    java.lang.Object ref = sampleId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sampleId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The sample identifier 
   * </pre>
   *
   * <code>string SampleId = 3;</code>
   * @return The bytes for sampleId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSampleIdBytes() {
    java.lang.Object ref = sampleId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sampleId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCANSTARTTIME_FIELD_NUMBER = 4;
  private double scanStartTime_ = 0D;
  /**
   * <pre>
   * The time that an analyzer started a scan, relative 
   * to the start of the MS run.
   * see also 
   * MS:1000016 for the description 
   * Units of Measure  UO:0000031 - minute
   * </pre>
   *
   * <code>double ScanStartTime = 4;</code>
   * @return The scanStartTime.
   */
  @java.lang.Override
  public double getScanStartTime() {
    return scanStartTime_;
  }

  public static final int DATA_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData> data_;
  /**
   * <pre>
   * the actual binary data. 
   * Usually, there will be at least 2 collections ( Xs and Ys ) 
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
   */
  @java.lang.Override
  public java.util.List<io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData> getDataList() {
    return data_;
  }
  /**
   * <pre>
   * the actual binary data. 
   * Usually, there will be at least 2 collections ( Xs and Ys ) 
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryDataOrBuilder> 
      getDataOrBuilderList() {
    return data_;
  }
  /**
   * <pre>
   * the actual binary data. 
   * Usually, there will be at least 2 collections ( Xs and Ys ) 
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
   */
  @java.lang.Override
  public int getDataCount() {
    return data_.size();
  }
  /**
   * <pre>
   * the actual binary data. 
   * Usually, there will be at least 2 collections ( Xs and Ys ) 
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
   */
  @java.lang.Override
  public io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData getData(int index) {
    return data_.get(index);
  }
  /**
   * <pre>
   * the actual binary data. 
   * Usually, there will be at least 2 collections ( Xs and Ys ) 
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
   */
  @java.lang.Override
  public io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryDataOrBuilder getDataOrBuilder(
      int index) {
    return data_.get(index);
  }

  public static final int PRECURSOR_FIELD_NUMBER = 6;
  private io.github.mzmine.modules.io.import_rawdata_wiff2.api.Precursor precursor_;
  /**
   * <pre>
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.Precursor Precursor = 6;</code>
   * @return Whether the precursor field is set.
   */
  @java.lang.Override
  public boolean hasPrecursor() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.Precursor Precursor = 6;</code>
   * @return The precursor.
   */
  @java.lang.Override
  public io.github.mzmine.modules.io.import_rawdata_wiff2.api.Precursor getPrecursor() {
    return precursor_ == null ? io.github.mzmine.modules.io.import_rawdata_wiff2.api.Precursor.getDefaultInstance() : precursor_;
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.Precursor Precursor = 6;</code>
   */
  @java.lang.Override
  public io.github.mzmine.modules.io.import_rawdata_wiff2.api.PrecursorOrBuilder getPrecursorOrBuilder() {
    return precursor_ == null ? io.github.mzmine.modules.io.import_rawdata_wiff2.api.Precursor.getDefaultInstance() : precursor_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(experimentId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, experimentId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sampleId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, sampleId_);
    }
    if (java.lang.Double.doubleToRawLongBits(scanStartTime_) != 0) {
      output.writeDouble(4, scanStartTime_);
    }
    for (int i = 0; i < data_.size(); i++) {
      output.writeMessage(5, data_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(6, getPrecursor());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(experimentId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, experimentId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sampleId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, sampleId_);
    }
    if (java.lang.Double.doubleToRawLongBits(scanStartTime_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, scanStartTime_);
    }
    for (int i = 0; i < data_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, data_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getPrecursor());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum)) {
      return super.equals(obj);
    }
    io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum other = (io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getExperimentId()
        .equals(other.getExperimentId())) return false;
    if (!getSampleId()
        .equals(other.getSampleId())) return false;
    if (java.lang.Double.doubleToLongBits(getScanStartTime())
        != java.lang.Double.doubleToLongBits(
            other.getScanStartTime())) return false;
    if (!getDataList()
        .equals(other.getDataList())) return false;
    if (hasPrecursor() != other.hasPrecursor()) return false;
    if (hasPrecursor()) {
      if (!getPrecursor()
          .equals(other.getPrecursor())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + EXPERIMENTID_FIELD_NUMBER;
    hash = (53 * hash) + getExperimentId().hashCode();
    hash = (37 * hash) + SAMPLEID_FIELD_NUMBER;
    hash = (53 * hash) + getSampleId().hashCode();
    hash = (37 * hash) + SCANSTARTTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getScanStartTime()));
    if (getDataCount() > 0) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getDataList().hashCode();
    }
    if (hasPrecursor()) {
      hash = (37 * hash) + PRECURSOR_FIELD_NUMBER;
      hash = (53 * hash) + getPrecursor().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The structure that captures the generation of a peak list 
   * (including the underlying acquisitions). Also describes some 
   * of the parameters for the mass spectrometer for a given 
   * acquisition (or list of acquisitions).
   * </pre>
   *
   * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.Spectrum}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Clearcore2.SampleData.DataAccessApi.V002.Spectrum)
      io.github.mzmine.modules.io.import_rawdata_wiff2.api.SpectrumOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_Spectrum_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_Spectrum_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum.class, io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum.Builder.class);
    }

    // Construct using io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetDataFieldBuilder();
        internalGetPrecursorFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      experimentId_ = "";
      sampleId_ = "";
      scanStartTime_ = 0D;
      if (dataBuilder_ == null) {
        data_ = java.util.Collections.emptyList();
      } else {
        data_ = null;
        dataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      precursor_ = null;
      if (precursorBuilder_ != null) {
        precursorBuilder_.dispose();
        precursorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_Spectrum_descriptor;
    }

    @java.lang.Override
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum getDefaultInstanceForType() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum build() {
      io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum buildPartial() {
      io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum result = new io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum result) {
      if (dataBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
    }

    private void buildPartial0(io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.experimentId_ = experimentId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.sampleId_ = sampleId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.scanStartTime_ = scanStartTime_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.precursor_ = precursorBuilder_ == null
            ? precursor_
            : precursorBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum) {
        return mergeFrom((io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum other) {
      if (other == io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getExperimentId().isEmpty()) {
        experimentId_ = other.experimentId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getSampleId().isEmpty()) {
        sampleId_ = other.sampleId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (java.lang.Double.doubleToRawLongBits(other.getScanStartTime()) != 0) {
        setScanStartTime(other.getScanStartTime());
      }
      if (dataBuilder_ == null) {
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
      } else {
        if (!other.data_.isEmpty()) {
          if (dataBuilder_.isEmpty()) {
            dataBuilder_.dispose();
            dataBuilder_ = null;
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000010);
            dataBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetDataFieldBuilder() : null;
          } else {
            dataBuilder_.addAllMessages(other.data_);
          }
        }
      }
      if (other.hasPrecursor()) {
        mergePrecursor(other.getPrecursor());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              experimentId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              sampleId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 33: {
              scanStartTime_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 42: {
              io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData m =
                  input.readMessage(
                      io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.parser(),
                      extensionRegistry);
              if (dataBuilder_ == null) {
                ensureDataIsMutable();
                data_.add(m);
              } else {
                dataBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  internalGetPrecursorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * the Id of the spectrum
     * </pre>
     *
     * <code>string Id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * the Id of the spectrum
     * </pre>
     *
     * <code>string Id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * the Id of the spectrum
     * </pre>
     *
     * <code>string Id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the Id of the spectrum
     * </pre>
     *
     * <code>string Id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the Id of the spectrum
     * </pre>
     *
     * <code>string Id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object experimentId_ = "";
    /**
     * <pre>
     * The id of the experiment used to acquire this spectrum
     * </pre>
     *
     * <code>string ExperimentId = 2;</code>
     * @return The experimentId.
     */
    public java.lang.String getExperimentId() {
      java.lang.Object ref = experimentId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        experimentId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The id of the experiment used to acquire this spectrum
     * </pre>
     *
     * <code>string ExperimentId = 2;</code>
     * @return The bytes for experimentId.
     */
    public com.google.protobuf.ByteString
        getExperimentIdBytes() {
      java.lang.Object ref = experimentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        experimentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The id of the experiment used to acquire this spectrum
     * </pre>
     *
     * <code>string ExperimentId = 2;</code>
     * @param value The experimentId to set.
     * @return This builder for chaining.
     */
    public Builder setExperimentId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      experimentId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The id of the experiment used to acquire this spectrum
     * </pre>
     *
     * <code>string ExperimentId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExperimentId() {
      experimentId_ = getDefaultInstance().getExperimentId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The id of the experiment used to acquire this spectrum
     * </pre>
     *
     * <code>string ExperimentId = 2;</code>
     * @param value The bytes for experimentId to set.
     * @return This builder for chaining.
     */
    public Builder setExperimentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      experimentId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object sampleId_ = "";
    /**
     * <pre>
     * The sample identifier 
     * </pre>
     *
     * <code>string SampleId = 3;</code>
     * @return The sampleId.
     */
    public java.lang.String getSampleId() {
      java.lang.Object ref = sampleId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sampleId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The sample identifier 
     * </pre>
     *
     * <code>string SampleId = 3;</code>
     * @return The bytes for sampleId.
     */
    public com.google.protobuf.ByteString
        getSampleIdBytes() {
      java.lang.Object ref = sampleId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sampleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The sample identifier 
     * </pre>
     *
     * <code>string SampleId = 3;</code>
     * @param value The sampleId to set.
     * @return This builder for chaining.
     */
    public Builder setSampleId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sampleId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The sample identifier 
     * </pre>
     *
     * <code>string SampleId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSampleId() {
      sampleId_ = getDefaultInstance().getSampleId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The sample identifier 
     * </pre>
     *
     * <code>string SampleId = 3;</code>
     * @param value The bytes for sampleId to set.
     * @return This builder for chaining.
     */
    public Builder setSampleIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sampleId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private double scanStartTime_ ;
    /**
     * <pre>
     * The time that an analyzer started a scan, relative 
     * to the start of the MS run.
     * see also 
     * MS:1000016 for the description 
     * Units of Measure  UO:0000031 - minute
     * </pre>
     *
     * <code>double ScanStartTime = 4;</code>
     * @return The scanStartTime.
     */
    @java.lang.Override
    public double getScanStartTime() {
      return scanStartTime_;
    }
    /**
     * <pre>
     * The time that an analyzer started a scan, relative 
     * to the start of the MS run.
     * see also 
     * MS:1000016 for the description 
     * Units of Measure  UO:0000031 - minute
     * </pre>
     *
     * <code>double ScanStartTime = 4;</code>
     * @param value The scanStartTime to set.
     * @return This builder for chaining.
     */
    public Builder setScanStartTime(double value) {

      scanStartTime_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The time that an analyzer started a scan, relative 
     * to the start of the MS run.
     * see also 
     * MS:1000016 for the description 
     * Units of Measure  UO:0000031 - minute
     * </pre>
     *
     * <code>double ScanStartTime = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearScanStartTime() {
      bitField0_ = (bitField0_ & ~0x00000008);
      scanStartTime_ = 0D;
      onChanged();
      return this;
    }

    private java.util.List<io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData> data_ =
      java.util.Collections.emptyList();
    private void ensureDataIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        data_ = new java.util.ArrayList<io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData>(data_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData, io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.Builder, io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryDataOrBuilder> dataBuilder_;

    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
     */
    public java.util.List<io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData> getDataList() {
      if (dataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(data_);
      } else {
        return dataBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
     */
    public int getDataCount() {
      if (dataBuilder_ == null) {
        return data_.size();
      } else {
        return dataBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData getData(int index) {
      if (dataBuilder_ == null) {
        return data_.get(index);
      } else {
        return dataBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
     */
    public Builder setData(
        int index, io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
      } else {
        dataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
     */
    public Builder setData(
        int index, io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.set(index, builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
     */
    public Builder addData(io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
      } else {
        dataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
     */
    public Builder addData(
        int index, io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.add(index, value);
        onChanged();
      } else {
        dataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
     */
    public Builder addData(
        io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.add(builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
     */
    public Builder addData(
        int index, io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.add(index, builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
     */
    public Builder addAllData(
        java.lang.Iterable<? extends io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData> values) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
      } else {
        dataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        dataBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
     */
    public Builder removeData(int index) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.remove(index);
        onChanged();
      } else {
        dataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.Builder getDataBuilder(
        int index) {
      return internalGetDataFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryDataOrBuilder getDataOrBuilder(
        int index) {
      if (dataBuilder_ == null) {
        return data_.get(index);  } else {
        return dataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
     */
    public java.util.List<? extends io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryDataOrBuilder> 
         getDataOrBuilderList() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(data_);
      }
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.Builder addDataBuilder() {
      return internalGetDataFieldBuilder().addBuilder(
          io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.getDefaultInstance());
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.Builder addDataBuilder(
        int index) {
      return internalGetDataFieldBuilder().addBuilder(
          index, io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.getDefaultInstance());
    }
    /**
     * <pre>
     * the actual binary data. 
     * Usually, there will be at least 2 collections ( Xs and Ys ) 
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
     */
    public java.util.List<io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.Builder> 
         getDataBuilderList() {
      return internalGetDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData, io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.Builder, io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryDataOrBuilder> 
        internalGetDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData, io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.Builder, io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryDataOrBuilder>(
                data_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }

    private io.github.mzmine.modules.io.import_rawdata_wiff2.api.Precursor precursor_;
    private com.google.protobuf.SingleFieldBuilder<
        io.github.mzmine.modules.io.import_rawdata_wiff2.api.Precursor, io.github.mzmine.modules.io.import_rawdata_wiff2.api.Precursor.Builder, io.github.mzmine.modules.io.import_rawdata_wiff2.api.PrecursorOrBuilder> precursorBuilder_;
    /**
     * <pre>
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.Precursor Precursor = 6;</code>
     * @return Whether the precursor field is set.
     */
    public boolean hasPrecursor() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.Precursor Precursor = 6;</code>
     * @return The precursor.
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.Precursor getPrecursor() {
      if (precursorBuilder_ == null) {
        return precursor_ == null ? io.github.mzmine.modules.io.import_rawdata_wiff2.api.Precursor.getDefaultInstance() : precursor_;
      } else {
        return precursorBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.Precursor Precursor = 6;</code>
     */
    public Builder setPrecursor(io.github.mzmine.modules.io.import_rawdata_wiff2.api.Precursor value) {
      if (precursorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        precursor_ = value;
      } else {
        precursorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.Precursor Precursor = 6;</code>
     */
    public Builder setPrecursor(
        io.github.mzmine.modules.io.import_rawdata_wiff2.api.Precursor.Builder builderForValue) {
      if (precursorBuilder_ == null) {
        precursor_ = builderForValue.build();
      } else {
        precursorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.Precursor Precursor = 6;</code>
     */
    public Builder mergePrecursor(io.github.mzmine.modules.io.import_rawdata_wiff2.api.Precursor value) {
      if (precursorBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          precursor_ != null &&
          precursor_ != io.github.mzmine.modules.io.import_rawdata_wiff2.api.Precursor.getDefaultInstance()) {
          getPrecursorBuilder().mergeFrom(value);
        } else {
          precursor_ = value;
        }
      } else {
        precursorBuilder_.mergeFrom(value);
      }
      if (precursor_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.Precursor Precursor = 6;</code>
     */
    public Builder clearPrecursor() {
      bitField0_ = (bitField0_ & ~0x00000020);
      precursor_ = null;
      if (precursorBuilder_ != null) {
        precursorBuilder_.dispose();
        precursorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.Precursor Precursor = 6;</code>
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.Precursor.Builder getPrecursorBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return internalGetPrecursorFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.Precursor Precursor = 6;</code>
     */
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.PrecursorOrBuilder getPrecursorOrBuilder() {
      if (precursorBuilder_ != null) {
        return precursorBuilder_.getMessageOrBuilder();
      } else {
        return precursor_ == null ?
            io.github.mzmine.modules.io.import_rawdata_wiff2.api.Precursor.getDefaultInstance() : precursor_;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.Precursor Precursor = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.github.mzmine.modules.io.import_rawdata_wiff2.api.Precursor, io.github.mzmine.modules.io.import_rawdata_wiff2.api.Precursor.Builder, io.github.mzmine.modules.io.import_rawdata_wiff2.api.PrecursorOrBuilder> 
        internalGetPrecursorFieldBuilder() {
      if (precursorBuilder_ == null) {
        precursorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.github.mzmine.modules.io.import_rawdata_wiff2.api.Precursor, io.github.mzmine.modules.io.import_rawdata_wiff2.api.Precursor.Builder, io.github.mzmine.modules.io.import_rawdata_wiff2.api.PrecursorOrBuilder>(
                getPrecursor(),
                getParentForChildren(),
                isClean());
        precursor_ = null;
      }
      return precursorBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:Clearcore2.SampleData.DataAccessApi.V002.Spectrum)
  }

  // @@protoc_insertion_point(class_scope:Clearcore2.SampleData.DataAccessApi.V002.Spectrum)
  private static final io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum();
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Spectrum>
      PARSER = new com.google.protobuf.AbstractParser<Spectrum>() {
    @java.lang.Override
    public Spectrum parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Spectrum> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Spectrum> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.mzmine.modules.io.import_rawdata_wiff2.api.Spectrum getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

