// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

@com.google.protobuf.Generated
public interface SpectrumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Clearcore2.SampleData.DataAccessApi.V002.Spectrum)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the Id of the spectrum
   * </pre>
   *
   * <code>string Id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * the Id of the spectrum
   * </pre>
   *
   * <code>string Id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * The id of the experiment used to acquire this spectrum
   * </pre>
   *
   * <code>string ExperimentId = 2;</code>
   * @return The experimentId.
   */
  java.lang.String getExperimentId();
  /**
   * <pre>
   * The id of the experiment used to acquire this spectrum
   * </pre>
   *
   * <code>string ExperimentId = 2;</code>
   * @return The bytes for experimentId.
   */
  com.google.protobuf.ByteString
      getExperimentIdBytes();

  /**
   * <pre>
   * The sample identifier 
   * </pre>
   *
   * <code>string SampleId = 3;</code>
   * @return The sampleId.
   */
  java.lang.String getSampleId();
  /**
   * <pre>
   * The sample identifier 
   * </pre>
   *
   * <code>string SampleId = 3;</code>
   * @return The bytes for sampleId.
   */
  com.google.protobuf.ByteString
      getSampleIdBytes();

  /**
   * <pre>
   * The time that an analyzer started a scan, relative 
   * to the start of the MS run.
   * see also 
   * MS:1000016 for the description 
   * Units of Measure  UO:0000031 - minute
   * </pre>
   *
   * <code>double ScanStartTime = 4;</code>
   * @return The scanStartTime.
   */
  double getScanStartTime();

  /**
   * <pre>
   * the actual binary data. 
   * Usually, there will be at least 2 collections ( Xs and Ys ) 
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
   */
  java.util.List<io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData> 
      getDataList();
  /**
   * <pre>
   * the actual binary data. 
   * Usually, there will be at least 2 collections ( Xs and Ys ) 
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
   */
  io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData getData(int index);
  /**
   * <pre>
   * the actual binary data. 
   * Usually, there will be at least 2 collections ( Xs and Ys ) 
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
   */
  int getDataCount();
  /**
   * <pre>
   * the actual binary data. 
   * Usually, there will be at least 2 collections ( Xs and Ys ) 
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
   */
  java.util.List<? extends io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryDataOrBuilder> 
      getDataOrBuilderList();
  /**
   * <pre>
   * the actual binary data. 
   * Usually, there will be at least 2 collections ( Xs and Ys ) 
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.BinaryData Data = 5;</code>
   */
  io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryDataOrBuilder getDataOrBuilder(
      int index);

  /**
   * <pre>
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.Precursor Precursor = 6;</code>
   * @return Whether the precursor field is set.
   */
  boolean hasPrecursor();
  /**
   * <pre>
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.Precursor Precursor = 6;</code>
   * @return The precursor.
   */
  io.github.mzmine.modules.io.import_rawdata_wiff2.api.Precursor getPrecursor();
  /**
   * <pre>
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.Precursor Precursor = 6;</code>
   */
  io.github.mzmine.modules.io.import_rawdata_wiff2.api.PrecursorOrBuilder getPrecursorOrBuilder();
}
