// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

@com.google.protobuf.Generated
public interface TableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Clearcore2.SampleData.DataAccessApi.V002.Table)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Get the Parameters.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 1;</code>
   */
  java.util.List<Parameter>
      getParametersList();
  /**
   * <pre>
   * Get the Parameters.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 1;</code>
   */
  Parameter getParameters(int index);
  /**
   * <pre>
   * Get the Parameters.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 1;</code>
   */
  int getParametersCount();
  /**
   * <pre>
   * Get the Parameters.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 1;</code>
   */
  java.util.List<? extends ParameterOrBuilder>
      getParametersOrBuilderList();
  /**
   * <pre>
   * Get the Parameters.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 1;</code>
   */
  ParameterOrBuilder getParametersOrBuilder(
      int index);

  /**
   * <pre>
   * Get the table parameters.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Columns = 2;</code>
   */
  java.util.List<Parameter>
      getColumnsList();
  /**
   * <pre>
   * Get the table parameters.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Columns = 2;</code>
   */
  Parameter getColumns(int index);
  /**
   * <pre>
   * Get the table parameters.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Columns = 2;</code>
   */
  int getColumnsCount();
  /**
   * <pre>
   * Get the table parameters.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Columns = 2;</code>
   */
  java.util.List<? extends ParameterOrBuilder>
      getColumnsOrBuilderList();
  /**
   * <pre>
   * Get the table parameters.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Columns = 2;</code>
   */
  ParameterOrBuilder getColumnsOrBuilder(
      int index);
}
