// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

/**
 * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.TofInstrumentParameters}
 */
@com.google.protobuf.Generated
public final class TofInstrumentParameters extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Clearcore2.SampleData.DataAccessApi.V002.TofInstrumentParameters)
    TofInstrumentParametersOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "TofInstrumentParameters");
  }
  // Use TofInstrumentParameters.newBuilder() to construct.
  private TofInstrumentParameters(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TofInstrumentParameters() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_TofInstrumentParameters_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_TofInstrumentParameters_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters.class, io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters.Builder.class);
  }

  public static final int TIMEBINSTOSUM_FIELD_NUMBER = 1;
  private int timeBinsToSum_ = 0;
  /**
   * <pre>
   * the number of detector time bins which were summed to generate a single (time, intensity) data point.
   * </pre>
   *
   * <code>int32 TimeBinsToSum = 1;</code>
   * @return The timeBinsToSum.
   */
  @java.lang.Override
  public int getTimeBinsToSum() {
    return timeBinsToSum_;
  }

  public static final int TDCRESOLUTION_FIELD_NUMBER = 2;
  private double tdcResolution_ = 0D;
  /**
   * <pre>
   * resolution of the TDC. This value will be 0 if there is no scan data in an experiment.
   * </pre>
   *
   * <code>double TdcResolution = 2;</code>
   * @return The tdcResolution.
   */
  @java.lang.Override
  public double getTdcResolution() {
    return tdcResolution_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timeBinsToSum_ != 0) {
      output.writeInt32(1, timeBinsToSum_);
    }
    if (java.lang.Double.doubleToRawLongBits(tdcResolution_) != 0) {
      output.writeDouble(2, tdcResolution_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timeBinsToSum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, timeBinsToSum_);
    }
    if (java.lang.Double.doubleToRawLongBits(tdcResolution_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, tdcResolution_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters)) {
      return super.equals(obj);
    }
    io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters other = (io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters) obj;

    if (getTimeBinsToSum()
        != other.getTimeBinsToSum()) return false;
    if (java.lang.Double.doubleToLongBits(getTdcResolution())
        != java.lang.Double.doubleToLongBits(
            other.getTdcResolution())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMEBINSTOSUM_FIELD_NUMBER;
    hash = (53 * hash) + getTimeBinsToSum();
    hash = (37 * hash) + TDCRESOLUTION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTdcResolution()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.TofInstrumentParameters}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Clearcore2.SampleData.DataAccessApi.V002.TofInstrumentParameters)
      io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParametersOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_TofInstrumentParameters_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_TofInstrumentParameters_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters.class, io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters.Builder.class);
    }

    // Construct using io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      timeBinsToSum_ = 0;
      tdcResolution_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_TofInstrumentParameters_descriptor;
    }

    @java.lang.Override
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters getDefaultInstanceForType() {
      return io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters build() {
      io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters buildPartial() {
      io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters result = new io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.timeBinsToSum_ = timeBinsToSum_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tdcResolution_ = tdcResolution_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters) {
        return mergeFrom((io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters other) {
      if (other == io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters.getDefaultInstance()) return this;
      if (other.getTimeBinsToSum() != 0) {
        setTimeBinsToSum(other.getTimeBinsToSum());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getTdcResolution()) != 0) {
        setTdcResolution(other.getTdcResolution());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              timeBinsToSum_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 17: {
              tdcResolution_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int timeBinsToSum_ ;
    /**
     * <pre>
     * the number of detector time bins which were summed to generate a single (time, intensity) data point.
     * </pre>
     *
     * <code>int32 TimeBinsToSum = 1;</code>
     * @return The timeBinsToSum.
     */
    @java.lang.Override
    public int getTimeBinsToSum() {
      return timeBinsToSum_;
    }
    /**
     * <pre>
     * the number of detector time bins which were summed to generate a single (time, intensity) data point.
     * </pre>
     *
     * <code>int32 TimeBinsToSum = 1;</code>
     * @param value The timeBinsToSum to set.
     * @return This builder for chaining.
     */
    public Builder setTimeBinsToSum(int value) {

      timeBinsToSum_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the number of detector time bins which were summed to generate a single (time, intensity) data point.
     * </pre>
     *
     * <code>int32 TimeBinsToSum = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeBinsToSum() {
      bitField0_ = (bitField0_ & ~0x00000001);
      timeBinsToSum_ = 0;
      onChanged();
      return this;
    }

    private double tdcResolution_ ;
    /**
     * <pre>
     * resolution of the TDC. This value will be 0 if there is no scan data in an experiment.
     * </pre>
     *
     * <code>double TdcResolution = 2;</code>
     * @return The tdcResolution.
     */
    @java.lang.Override
    public double getTdcResolution() {
      return tdcResolution_;
    }
    /**
     * <pre>
     * resolution of the TDC. This value will be 0 if there is no scan data in an experiment.
     * </pre>
     *
     * <code>double TdcResolution = 2;</code>
     * @param value The tdcResolution to set.
     * @return This builder for chaining.
     */
    public Builder setTdcResolution(double value) {

      tdcResolution_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * resolution of the TDC. This value will be 0 if there is no scan data in an experiment.
     * </pre>
     *
     * <code>double TdcResolution = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTdcResolution() {
      bitField0_ = (bitField0_ & ~0x00000002);
      tdcResolution_ = 0D;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Clearcore2.SampleData.DataAccessApi.V002.TofInstrumentParameters)
  }

  // @@protoc_insertion_point(class_scope:Clearcore2.SampleData.DataAccessApi.V002.TofInstrumentParameters)
  private static final io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters();
  }

  public static io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TofInstrumentParameters>
      PARSER = new com.google.protobuf.AbstractParser<TofInstrumentParameters>() {
    @java.lang.Override
    public TofInstrumentParameters parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TofInstrumentParameters> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TofInstrumentParameters> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.mzmine.modules.io.import_rawdata_wiff2.api.TofInstrumentParameters getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

