{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "memory-management",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "memory-management-1.0.0.jar",
          "url": "memory-management-1.0.0.jar",
          "size": 4843,
          "sha512": "58185e65afe97042cb49739f2243599af0ab5cc3910e911379584516826d78e31d6df9504223a61ee7ed04004e51a0bf2d37774b91daa5c7ef42135636e2fe96",
          "sha256": "f78deb1146bd7259a40b9663882aeda626134498276458cc873998aab1dc0092",
          "sha1": "8430865c04fbee6c2edbfa04fa5b1e4c48206e21",
          "md5": "3c02d2e40d397fac2666004a3dc23799"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "io.github.mzmine",
          "module": "utils"
        }
      ],
      "files": [
        {
          "name": "memory-management-1.0.0.jar",
          "url": "memory-management-1.0.0.jar",
          "size": 4843,
          "sha512": "58185e65afe97042cb49739f2243599af0ab5cc3910e911379584516826d78e31d6df9504223a61ee7ed04004e51a0bf2d37774b91daa5c7ef42135636e2fe96",
          "sha256": "f78deb1146bd7259a40b9663882aeda626134498276458cc873998aab1dc0092",
          "sha1": "8430865c04fbee6c2edbfa04fa5b1e4c48206e21",
          "md5": "3c02d2e40d397fac2666004a3dc23799"
        }
      ]
    }
  ]
}
