{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "memory-management",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "memory-management-1.0.0.jar",
          "url": "memory-management-1.0.0.jar",
          "size": 8014,
          "sha512": "c44a383770a0f4d780ab680111f3f5ac0be4c05d23d359e00135c235e9628a2edafcbfed8b444af78a2640d1388150aa1d810f0ce70b97df6182ebb8d099c18a",
          "sha256": "efedc512926fdcd530db7a0714e67882454e57d56606edeaef0bc9f9397bae0c",
          "sha1": "f3124fc75d95dfb847e7ddd15a06e8da45a87660",
          "md5": "c6562fbf81f070a9ba8a9eae4b52501c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "io.github.mzmine",
          "module": "utils"
        }
      ],
      "files": [
        {
          "name": "memory-management-1.0.0.jar",
          "url": "memory-management-1.0.0.jar",
          "size": 8014,
          "sha512": "c44a383770a0f4d780ab680111f3f5ac0be4c05d23d359e00135c235e9628a2edafcbfed8b444af78a2640d1388150aa1d810f0ce70b97df6182ebb8d099c18a",
          "sha256": "efedc512926fdcd530db7a0714e67882454e57d56606edeaef0bc9f9397bae0c",
          "sha1": "f3124fc75d95dfb847e7ddd15a06e8da45a87660",
          "md5": "c6562fbf81f070a9ba8a9eae4b52501c"
        }
      ]
    }
  ]
}
